<?php
    $version = '1.6'; // the $ projectnumber variable is automatically replaced by doxygen with the version number
    $pagetitle = 'Member List'; // the $ title variable is automatically replaced by doxygen with the page title
    include('../header-fr.php');
?>
<!-- Generated by Doxygen 1.8.2 -->
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="classes.php"><span>Class&#160;Index</span></a></li>
      <li><a href="hierarchy.php"><span>Class&#160;Hierarchy</span></a></li>
      <li><a href="functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><b>sf</b></li><li class="navelem"><a class="el" href="classsf_1_1IPAddress.php">IPAddress</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="headertitle">
<div class="title">sf::IPAddress Member List</div>  </div>
</div><!--header-->
<div class="contents">

<p>This is the complete list of members for <a class="el" href="classsf_1_1IPAddress.php">sf::IPAddress</a>, including all inherited members.</p>
<table class="directory">
  <tr class="even"><td class="entry"><a class="el" href="classsf_1_1IPAddress.php#a19de85dde974ff66e0b0255cce5eedac">GetLocalAddress</a>()</td><td class="entry"><a class="el" href="classsf_1_1IPAddress.php">sf::IPAddress</a></td><td class="entry"><span class="mlabel">static</span></td></tr>
  <tr><td class="entry"><a class="el" href="classsf_1_1IPAddress.php#aad0feeaf81c7a15166a003773faa1ba6">GetPublicAddress</a>(float Timeout=0.f)</td><td class="entry"><a class="el" href="classsf_1_1IPAddress.php">sf::IPAddress</a></td><td class="entry"><span class="mlabel">static</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="classsf_1_1IPAddress.php#ad0d6a00a3fd597aab4b86f2bc5a85831">IPAddress</a>()</td><td class="entry"><a class="el" href="classsf_1_1IPAddress.php">sf::IPAddress</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="classsf_1_1IPAddress.php#adf8d2e87ea8076b627c3e7254b5e4039">IPAddress</a>(const std::string &amp;Address)</td><td class="entry"><a class="el" href="classsf_1_1IPAddress.php">sf::IPAddress</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="classsf_1_1IPAddress.php#a00c1b422265e1261509d5030534bfb0f">IPAddress</a>(const char *Address)</td><td class="entry"><a class="el" href="classsf_1_1IPAddress.php">sf::IPAddress</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="classsf_1_1IPAddress.php#a16fa44fa881e32a03b67006d90db0c39">IPAddress</a>(Uint8 Byte0, Uint8 Byte1, Uint8 Byte2, Uint8 Byte3)</td><td class="entry"><a class="el" href="classsf_1_1IPAddress.php">sf::IPAddress</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="classsf_1_1IPAddress.php#ad692d581e4b96ae3377e95947abb7565">IPAddress</a>(Uint32 Address)</td><td class="entry"><a class="el" href="classsf_1_1IPAddress.php">sf::IPAddress</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="classsf_1_1IPAddress.php#a943e91f407afa5d9ae9b988492385697">IsValid</a>() const </td><td class="entry"><a class="el" href="classsf_1_1IPAddress.php">sf::IPAddress</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="classsf_1_1IPAddress.php#a3529ec93755712b038fe6b1456c4f7e0">LocalHost</a></td><td class="entry"><a class="el" href="classsf_1_1IPAddress.php">sf::IPAddress</a></td><td class="entry"><span class="mlabel">static</span></td></tr>
  <tr><td class="entry"><a class="el" href="classsf_1_1IPAddress.php#adcab830aa4008d469c235582d90ae104">operator!=</a>(const IPAddress &amp;Other) const </td><td class="entry"><a class="el" href="classsf_1_1IPAddress.php">sf::IPAddress</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="classsf_1_1IPAddress.php#a90ca315772725588df2a5fe73565cb3e">operator&lt;</a>(const IPAddress &amp;Other) const </td><td class="entry"><a class="el" href="classsf_1_1IPAddress.php">sf::IPAddress</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="classsf_1_1IPAddress.php#ad9159e1fbdfffb81b45ac2518143c2be">operator&lt;=</a>(const IPAddress &amp;Other) const </td><td class="entry"><a class="el" href="classsf_1_1IPAddress.php">sf::IPAddress</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="classsf_1_1IPAddress.php#a326dc00d3ab26ada6ed3168460545b48">operator==</a>(const IPAddress &amp;Other) const </td><td class="entry"><a class="el" href="classsf_1_1IPAddress.php">sf::IPAddress</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="classsf_1_1IPAddress.php#a6cd4ab449515009f0d1ab0cd41ddbab0">operator&gt;</a>(const IPAddress &amp;Other) const </td><td class="entry"><a class="el" href="classsf_1_1IPAddress.php">sf::IPAddress</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="classsf_1_1IPAddress.php#a7b0f3e471d2286737023d80220a1313b">operator&gt;=</a>(const IPAddress &amp;Other) const </td><td class="entry"><a class="el" href="classsf_1_1IPAddress.php">sf::IPAddress</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="classsf_1_1IPAddress.php#aec6999cce584d3b275072cb6da839c3c">ToInteger</a>() const </td><td class="entry"><a class="el" href="classsf_1_1IPAddress.php">sf::IPAddress</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="classsf_1_1IPAddress.php#a76eadca85be545b5c1c68a4d0dc1c643">ToString</a>() const </td><td class="entry"><a class="el" href="classsf_1_1IPAddress.php">sf::IPAddress</a></td><td class="entry"></td></tr>
</table></div><!-- contents -->
<?php
    require("../footer-fr.php");
?>
