<?php
    $version = '1.6'; // the $ projectnumber variable is automatically replaced by doxygen with the version number
    $pagetitle = 'Class Members'; // the $ title variable is automatically replaced by doxygen with the page title
    include('../header-fr.php');
?>
<!-- Generated by Doxygen 1.8.2 -->
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="classes.php"><span>Class&#160;Index</span></a></li>
      <li><a href="hierarchy.php"><span>Class&#160;Hierarchy</span></a></li>
      <li class="current"><a href="functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
  <div id="navrow3" class="tabs2">
    <ul class="tablist">
      <li class="current"><a href="functions.php"><span>All</span></a></li>
      <li><a href="functions_func.php"><span>Functions</span></a></li>
      <li><a href="functions_vars.php"><span>Variables</span></a></li>
      <li><a href="functions_type.php"><span>Typedefs</span></a></li>
      <li><a href="functions_enum.php"><span>Enumerations</span></a></li>
      <li><a href="functions_eval.php"><span>Enumerator</span></a></li>
    </ul>
  </div>
  <div id="navrow4" class="tabs3">
    <ul class="tablist">
      <li><a href="functions.php#index_a"><span>a</span></a></li>
      <li><a href="functions_0x62.php#index_b"><span>b</span></a></li>
      <li class="current"><a href="functions_0x63.php#index_c"><span>c</span></a></li>
      <li><a href="functions_0x64.php#index_d"><span>d</span></a></li>
      <li><a href="functions_0x65.php#index_e"><span>e</span></a></li>
      <li><a href="functions_0x66.php#index_f"><span>f</span></a></li>
      <li><a href="functions_0x67.php#index_g"><span>g</span></a></li>
      <li><a href="functions_0x68.php#index_h"><span>h</span></a></li>
      <li><a href="functions_0x69.php#index_i"><span>i</span></a></li>
      <li><a href="functions_0x6b.php#index_k"><span>k</span></a></li>
      <li><a href="functions_0x6c.php#index_l"><span>l</span></a></li>
      <li><a href="functions_0x6d.php#index_m"><span>m</span></a></li>
      <li><a href="functions_0x6e.php#index_n"><span>n</span></a></li>
      <li><a href="functions_0x6f.php#index_o"><span>o</span></a></li>
      <li><a href="functions_0x70.php#index_p"><span>p</span></a></li>
      <li><a href="functions_0x72.php#index_r"><span>r</span></a></li>
      <li><a href="functions_0x73.php#index_s"><span>s</span></a></li>
      <li><a href="functions_0x74.php#index_t"><span>t</span></a></li>
      <li><a href="functions_0x75.php#index_u"><span>u</span></a></li>
      <li><a href="functions_0x76.php#index_v"><span>v</span></a></li>
      <li><a href="functions_0x77.php#index_w"><span>w</span></a></li>
      <li><a href="functions_0x78.php#index_x"><span>x</span></a></li>
      <li><a href="functions_0x79.php#index_y"><span>y</span></a></li>
      <li><a href="functions_0x7a.php#index_z"><span>z</span></a></li>
      <li><a href="functions_0x7e.php#index_0x7e"><span>~</span></a></li>
    </ul>
  </div>
</div><!-- top -->
<div class="contents">
<div class="textblock">Here is a list of all documented class members with links to the class documentation for each member:</div>

<h3><a class="anchor" id="index_c"></a>- c -</h3><ul>
<li>CanCapture()
: <a class="el" href="classsf_1_1SoundRecorder.php#afa49a0834d1b49ec69b9991f88558040">sf::SoundRecorder</a>
</li>
<li>CanUsePostFX()
: <a class="el" href="classsf_1_1PostFX.php#a9f6642b75c82e0e856951e71b77aa7e8">sf::PostFX</a>
</li>
<li>Capture()
: <a class="el" href="classsf_1_1RenderWindow.php#a7066f80705fb53c2c4a9fe068fc47a8a">sf::RenderWindow</a>
</li>
<li>ChangeDirectory()
: <a class="el" href="classsf_1_1Ftp.php#a4c3b2d61ea3b14512d62230c8d7ed16a">sf::Ftp</a>
</li>
<li>Circle()
: <a class="el" href="classsf_1_1Shape.php#ab92e46570354ecbfabd278bbde08905b">sf::Shape</a>
</li>
<li>Clear()
: <a class="el" href="classsf_1_1Packet.php#a3a7a30fb7a39e59df0cbd773756f60da">sf::Packet</a>
, <a class="el" href="classsf_1_1Selector.php#a92dcaf012e8effb02262717b10b1c6f4">sf::Selector&lt; Type &gt;</a>
, <a class="el" href="classsf_1_1SelectorBase.php#ae24ec8c1ac981b8411c1c209daf788d0">sf::SelectorBase</a>
, <a class="el" href="classsf_1_1RenderTarget.php#a125645088d7b2df07599ea36fbb8b87e">sf::RenderTarget</a>
</li>
<li>Clock()
: <a class="el" href="classsf_1_1Clock.php#abbc959c7830ca7c3a4da133cb506d3fd">sf::Clock</a>
</li>
<li>Close()
: <a class="el" href="classsf_1_1SocketTCP.php#a70a5111cbddd1edbfa6cbd6017c6d044">sf::SocketTCP</a>
, <a class="el" href="classsf_1_1SocketUDP.php#ac9abf54c9ced16b55ddef46973cd1a58">sf::SocketUDP</a>
, <a class="el" href="classsf_1_1SocketHelper.php#afeb8116b59837e7759b1424c998cc186">sf::SocketHelper</a>
, <a class="el" href="classsf_1_1Window.php#ab04439f6fb9fdfe40f882676fdb2938c">sf::Window</a>
</li>
<li>ClosingConnection
: <a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3bab23931490fc2d1df3081d651fe0f4d6e">sf::Ftp::Response</a>
</li>
<li>ClosingDataConnection
: <a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3bac723ebc8a38913bbf0d9504556cbaaa6">sf::Ftp::Response</a>
</li>
<li>Color()
: <a class="el" href="classsf_1_1Color.php#ac2eb4393fb11ad3fa3ccf34e92fe08e4">sf::Color</a>
</li>
<li>CommandNotImplemented
: <a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3ba2ca4834c756c81b924ebed696fcba0a8">sf::Ftp::Response</a>
</li>
<li>CommandUnknown
: <a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3ba75bdf0b6844fa9c07b3c25647d22c269">sf::Ftp::Response</a>
</li>
<li>Connect()
: <a class="el" href="classsf_1_1SocketTCP.php#add590d0119fa8edbe8da1574b6c8f07f">sf::SocketTCP</a>
, <a class="el" href="classsf_1_1Ftp.php#a8fee5fc52934a4dfef076303b71995d8">sf::Ftp</a>
</li>
<li>ConnectionClosed
: <a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3bad1e5dcf298ce30c528261435f1a2eb53">sf::Ftp::Response</a>
</li>
<li>ConnectionFailed
: <a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3ba51aa367cc1e85a45ea3c7be48730e990">sf::Ftp::Response</a>
, <a class="el" href="classsf_1_1Http_1_1Response.php#a663e071978e30fbbeb20ed045be874d8a7f307376f13bdc06b24fc274ecd2aa60">sf::Http::Response</a>
</li>
<li>Contains()
: <a class="el" href="classsf_1_1Rect.php#ab56c71b17e5edfaf4e4c839b8b4dfcb7">sf::Rect&lt; T &gt;</a>
</li>
<li>Context()
: <a class="el" href="classsf_1_1Context.php#aba22797a790706ca2c5c04ee39f2b555">sf::Context</a>
</li>
<li>ConvertCoords()
: <a class="el" href="classsf_1_1RenderWindow.php#a05c614a2cdc2c2c4e3b473e39b3b9a17">sf::RenderWindow</a>
</li>
<li>Copy()
: <a class="el" href="classsf_1_1Image.php#a408c40c8675363adfa96a8b9a9576bc2">sf::Image</a>
</li>
<li>CopyScreen()
: <a class="el" href="classsf_1_1Image.php#a96597746f70ce1925ec82d2df8ae6974">sf::Image</a>
</li>
<li>Create()
: <a class="el" href="classsf_1_1Window.php#aa891f1cbd7d77c4dc02ac950b6e76f61">sf::Window</a>
, <a class="el" href="classsf_1_1Image.php#a4e2ce8821e8de36462604bbf99f39cde">sf::Image</a>
, <a class="el" href="classsf_1_1Window.php#a58e264c181fd70e67986d26fea69a71d">sf::Window</a>
</li>
<li>Created
: <a class="el" href="classsf_1_1Http_1_1Response.php#a663e071978e30fbbeb20ed045be874d8a0a6e8bafa9365a0ed10b8a9cbfd0649b">sf::Http::Response</a>
</li>
<li>CreateMaskFromColor()
: <a class="el" href="classsf_1_1Image.php#ae9a15fe9a4750295845b5ae081c2ec50">sf::Image</a>
</li>
<li>Cyan
: <a class="el" href="classsf_1_1Color.php#a64ae9beb0b9a5865dd811cda4bb18340">sf::Color</a>
</li>
</ul>
</div><!-- contents -->
<?php
    require("../footer-fr.php");
?>
