<?php
    $version = '2.5.0'; // the $ projectnumber variable is automatically replaced by doxygen with the version number
    $pagetitle = 'Class Members'; // the $ title variable is automatically replaced by doxygen with the page title
    include('../header.php');
?>
<!-- Generated by Doxygen 1.8.14 -->
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="pages.php"><span>Related&#160;Pages</span></a></li>
      <li><a href="modules.php"><span>Modules</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="classes.php"><span>Class&#160;Index</span></a></li>
      <li><a href="inherits.php"><span>Class&#160;Hierarchy</span></a></li>
      <li class="current"><a href="functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
  <div id="navrow3" class="tabs2">
    <ul class="tablist">
      <li class="current"><a href="functions.php"><span>All</span></a></li>
      <li><a href="functions_func.php"><span>Functions</span></a></li>
      <li><a href="functions_vars.php"><span>Variables</span></a></li>
      <li><a href="functions_type.php"><span>Typedefs</span></a></li>
      <li><a href="functions_enum.php"><span>Enumerations</span></a></li>
      <li><a href="functions_eval.php"><span>Enumerator</span></a></li>
      <li><a href="functions_rela.php"><span>Related&#160;Functions</span></a></li>
    </ul>
  </div>
  <div id="navrow4" class="tabs3">
    <ul class="tablist">
      <li><a href="functions.php#index_a"><span>a</span></a></li>
      <li><a href="functions_b.php#index_b"><span>b</span></a></li>
      <li><a href="functions_c.php#index_c"><span>c</span></a></li>
      <li><a href="functions_d.php#index_d"><span>d</span></a></li>
      <li><a href="functions_e.php#index_e"><span>e</span></a></li>
      <li><a href="functions_f.php#index_f"><span>f</span></a></li>
      <li><a href="functions_g.php#index_g"><span>g</span></a></li>
      <li><a href="functions_h.php#index_h"><span>h</span></a></li>
      <li><a href="functions_i.php#index_i"><span>i</span></a></li>
      <li><a href="functions_j.php#index_j"><span>j</span></a></li>
      <li><a href="functions_k.php#index_k"><span>k</span></a></li>
      <li><a href="functions_l.php#index_l"><span>l</span></a></li>
      <li><a href="functions_m.php#index_m"><span>m</span></a></li>
      <li><a href="functions_n.php#index_n"><span>n</span></a></li>
      <li class="current"><a href="functions_o.php#index_o"><span>o</span></a></li>
      <li><a href="functions_p.php#index_p"><span>p</span></a></li>
      <li><a href="functions_q.php#index_q"><span>q</span></a></li>
      <li><a href="functions_r.php#index_r"><span>r</span></a></li>
      <li><a href="functions_s.php#index_s"><span>s</span></a></li>
      <li><a href="functions_t.php#index_t"><span>t</span></a></li>
      <li><a href="functions_u.php#index_u"><span>u</span></a></li>
      <li><a href="functions_v.php#index_v"><span>v</span></a></li>
      <li><a href="functions_w.php#index_w"><span>w</span></a></li>
      <li><a href="functions_x.php#index_x"><span>x</span></a></li>
      <li><a href="functions_y.php#index_y"><span>y</span></a></li>
      <li><a href="functions_z.php#index_z"><span>z</span></a></li>
      <li><a href="functions_0x7e.php#index_0x7e"><span>~</span></a></li>
    </ul>
  </div>
</div><!-- top -->
<div class="contents">
<div class="textblock">Here is a list of all documented class members with links to the class documentation for each member:</div>

<h3><a id="index_o"></a>- o -</h3><ul>
<li>O
: <a class="el" href="classsf_1_1Keyboard.php#acb4cacd7cc5802dec45724cf3314a142a7739288cc628dfa8c50ba712be7c03e1">sf::Keyboard</a>
</li>
<li>offset
: <a class="el" href="structsf_1_1Music_1_1Span.php#a49bb6a3c4239288cf47c1298c3e5e1a3">sf::Music::Span&lt; T &gt;</a>
</li>
<li>Ok
: <a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3baa956e229ba6c0cdf0d88b0e05b286210">sf::Ftp::Response</a>
, <a class="el" href="classsf_1_1Http_1_1Response.php#a663e071978e30fbbeb20ed045be874d8a0158f932254d3f09647dd1f64bd43832">sf::Http::Response</a>
</li>
<li>onCreate()
: <a class="el" href="classsf_1_1RenderWindow.php#a5bef0040b0fa87bed9fbd459c980d53a">sf::RenderWindow</a>
, <a class="el" href="classsf_1_1Window.php#a106633b9be49b27f83d4712689b493eb">sf::Window</a>
</li>
<li>One
: <a class="el" href="structsf_1_1BlendMode.php#afb9852caf356b53bb0de460c58a9ebbbaa2d3ba8b8bb2233c9d357cbb94bf4181">sf::BlendMode</a>
</li>
<li>OneMinusDstAlpha
: <a class="el" href="structsf_1_1BlendMode.php#afb9852caf356b53bb0de460c58a9ebbbab4e5c63f189f26075e5939ad1a2ce4e4">sf::BlendMode</a>
</li>
<li>OneMinusDstColor
: <a class="el" href="structsf_1_1BlendMode.php#afb9852caf356b53bb0de460c58a9ebbbac8198db20d14506a841d1091ced1cae2">sf::BlendMode</a>
</li>
<li>OneMinusSrcAlpha
: <a class="el" href="structsf_1_1BlendMode.php#afb9852caf356b53bb0de460c58a9ebbbaab57e8616bf4c21d8ee923178acdf2c8">sf::BlendMode</a>
</li>
<li>OneMinusSrcColor
: <a class="el" href="structsf_1_1BlendMode.php#afb9852caf356b53bb0de460c58a9ebbba5971ffdbca63382058ccba76bfce219e">sf::BlendMode</a>
</li>
<li>onGetData()
: <a class="el" href="classsf_1_1Music.php#aca1bcb4e5d56a854133e74bd86374463">sf::Music</a>
, <a class="el" href="classsf_1_1SoundStream.php#a968ec024a6e45490962c8a1121cb7c5f">sf::SoundStream</a>
</li>
<li>onLoop()
: <a class="el" href="classsf_1_1Music.php#aa68a64bdaf5d16e9ed64f202f5c45e03">sf::Music</a>
, <a class="el" href="classsf_1_1SoundStream.php#a3f717d18846f261fc375d71d6c7e41da">sf::SoundStream</a>
</li>
<li>onProcessSamples()
: <a class="el" href="classsf_1_1SoundBufferRecorder.php#a9ceb94de14632ae8c1b78faf603b4767">sf::SoundBufferRecorder</a>
, <a class="el" href="classsf_1_1SoundRecorder.php#a2670124cbe7a87c7e46b4840807f4fd7">sf::SoundRecorder</a>
</li>
<li>onReceive()
: <a class="el" href="classsf_1_1Packet.php#ab71a31ef0f1d5d856de6f9fc75434128">sf::Packet</a>
</li>
<li>onResize()
: <a class="el" href="classsf_1_1RenderWindow.php#a5c85fe482313562d33ffd24a194b6fef">sf::RenderWindow</a>
, <a class="el" href="classsf_1_1Window.php#a10f567a387da7b49f417f73321fcf64d">sf::Window</a>
</li>
<li>onSeek()
: <a class="el" href="classsf_1_1Music.php#a15119cc0419c16bb334fa0698699c02e">sf::Music</a>
, <a class="el" href="classsf_1_1SoundStream.php#a907036dd2ca7d3af5ead316e54b75997">sf::SoundStream</a>
</li>
<li>onSend()
: <a class="el" href="classsf_1_1Packet.php#a052e955906c9bfd671622cb625380edc">sf::Packet</a>
</li>
<li>onStart()
: <a class="el" href="classsf_1_1SoundBufferRecorder.php#a531a7445fc8a48eaf9fc039c83f17c6f">sf::SoundBufferRecorder</a>
, <a class="el" href="classsf_1_1SoundRecorder.php#a7af418fb036201d3f85745bef78ce77f">sf::SoundRecorder</a>
</li>
<li>onStop()
: <a class="el" href="classsf_1_1SoundBufferRecorder.php#ab8e53849312413431873a5869d509f1e">sf::SoundBufferRecorder</a>
, <a class="el" href="classsf_1_1SoundRecorder.php#aefc36138ca1e96c658301280e4a31b64">sf::SoundRecorder</a>
</li>
<li>open()
: <a class="el" href="classsf_1_1FileInputStream.php#a87a95dc3a71746097a99c86ee58bb353">sf::FileInputStream</a>
, <a class="el" href="classsf_1_1MemoryInputStream.php#ad3cfb4f4f915f7803d6a0784e394ac19">sf::MemoryInputStream</a>
, <a class="el" href="classsf_1_1SoundFileReader.php#aa1d2fee2ba8f359c833ab74590d55935">sf::SoundFileReader</a>
, <a class="el" href="classsf_1_1SoundFileWriter.php#a5c92bcaaa880ef4d3eaab18dae1d3d07">sf::SoundFileWriter</a>
</li>
<li>openFromFile()
: <a class="el" href="classsf_1_1InputSoundFile.php#af68e54bc9bfac19554c84601156fe93f">sf::InputSoundFile</a>
, <a class="el" href="classsf_1_1Music.php#a3edc66e5f5b3f11e84b90eaec9c7d7c0">sf::Music</a>
, <a class="el" href="classsf_1_1OutputSoundFile.php#ae5e55f01c53c1422c44eaed2eed67fce">sf::OutputSoundFile</a>
</li>
<li>openFromMemory()
: <a class="el" href="classsf_1_1InputSoundFile.php#a4e034a8e9e69ca3c33a3f11180250400">sf::InputSoundFile</a>
, <a class="el" href="classsf_1_1Music.php#ae93b21bcf28ff0b5fec458039111386e">sf::Music</a>
</li>
<li>openFromStream()
: <a class="el" href="classsf_1_1InputSoundFile.php#a32b76497aeb088a2b46dc6efd819b909">sf::InputSoundFile</a>
, <a class="el" href="classsf_1_1Music.php#a4e55d1910a26858b44778c26b237d673">sf::Music</a>
</li>
<li>OpeningDataConnection
: <a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3ba794ebe743688be611447638bf9e49d86">sf::Ftp::Response</a>
</li>
<li>operator BoolType()
: <a class="el" href="classsf_1_1Packet.php#a8ab20be4a63921b7cb1a4d8ca5c30f75">sf::Packet</a>
</li>
<li>operator std::string()
: <a class="el" href="classsf_1_1String.php#a884816a0f688cfd48f9324c9741dc257">sf::String</a>
</li>
<li>operator std::wstring()
: <a class="el" href="classsf_1_1String.php#a6bd1444bebaca9bbf01ba203061f5076">sf::String</a>
</li>
<li>operator T*()
: <a class="el" href="classsf_1_1ThreadLocalPtr.php#a81ca089ae5cda72c7470ca93041c3cb2">sf::ThreadLocalPtr&lt; T &gt;</a>
</li>
<li>operator!=()
: <a class="el" href="structsf_1_1BlendMode.php#aee6169f8983f5e92298c4ad6829563ba">sf::BlendMode</a>
, <a class="el" href="classsf_1_1Color.php#a394c3495753c4b17f9cd45556ef00b8c">sf::Color</a>
, <a class="el" href="classsf_1_1Rect.php#a03fc4c105687b7d0f07b6b4ed4b45581">sf::Rect&lt; T &gt;</a>
, <a class="el" href="classsf_1_1String.php#a3bfb9217788a9978499b8d5696bb0ef2">sf::String</a>
, <a class="el" href="classsf_1_1Time.php#a3a142729f295af8b1baf2d8762bc39ac">sf::Time</a>
, <a class="el" href="classsf_1_1Transform.php#a5eee840ff0b2db9e5f57a87281cc2b01">sf::Transform</a>
, <a class="el" href="classsf_1_1Vector2.php#a01673da35ef9c52d0e54b8263549a956">sf::Vector2&lt; T &gt;</a>
, <a class="el" href="classsf_1_1Vector3.php#a608500d1ad3b78082cb5bb4356742bd4">sf::Vector3&lt; T &gt;</a>
, <a class="el" href="classsf_1_1VideoMode.php#a34b5c266a7b9cd5bc95de62f8beafc5a">sf::VideoMode</a>
</li>
<li>operator%()
: <a class="el" href="classsf_1_1Time.php#abe7206e15c2bf7ce8695f82219d466d2">sf::Time</a>
</li>
<li>operator%=()
: <a class="el" href="classsf_1_1Time.php#a880fb0137cd426bd4457fd9e4a2f9d83">sf::Time</a>
</li>
<li>operator*()
: <a class="el" href="classsf_1_1Color.php#a1bae779fb49bb92dbf820a65e45a6602">sf::Color</a>
, <a class="el" href="classsf_1_1ThreadLocalPtr.php#ad31e8c4f342a676c759e921c08ad3343">sf::ThreadLocalPtr&lt; T &gt;</a>
, <a class="el" href="classsf_1_1Time.php#ab891d4f3dbb454f6c1c484a7844bb581">sf::Time</a>
, <a class="el" href="classsf_1_1Transform.php#a85ea4e5539795f9b2ceb7d4b06736c8f">sf::Transform</a>
, <a class="el" href="classsf_1_1Vector2.php#ad8b3e1cf7b156a984bc1427539ca8605">sf::Vector2&lt; T &gt;</a>
, <a class="el" href="classsf_1_1Vector3.php#a44ec312b31c1a85dcff4863795f98329">sf::Vector3&lt; T &gt;</a>
</li>
<li>operator*=()
: <a class="el" href="classsf_1_1Color.php#a7d1ea2b9bd5dbe29bb2e54feba9b4b38">sf::Color</a>
, <a class="el" href="classsf_1_1Time.php#a3f7baa961b8961fc5e6a37dea7de10e3">sf::Time</a>
, <a class="el" href="classsf_1_1Transform.php#a189899674616490f6250953ac581ac30">sf::Transform</a>
, <a class="el" href="classsf_1_1Vector2.php#abea24cb28c0d6e2957e259ba4e65d70e">sf::Vector2&lt; T &gt;</a>
, <a class="el" href="classsf_1_1Vector3.php#ad5fb972775ce8ab58cd9670789e806a7">sf::Vector3&lt; T &gt;</a>
</li>
<li>operator+()
: <a class="el" href="classsf_1_1Color.php#a0355ba6bfd2f83ffd8f8fafdca26cdd0">sf::Color</a>
, <a class="el" href="classsf_1_1String.php#af140f992b7698cf1448677c2c8e11bf1">sf::String</a>
, <a class="el" href="classsf_1_1Time.php#a8249d3a28c8062c7c46cc426186f76c8">sf::Time</a>
, <a class="el" href="classsf_1_1Vector2.php#a72421239823c38a6b780c86a710ead07">sf::Vector2&lt; T &gt;</a>
, <a class="el" href="classsf_1_1Vector3.php#a6500a0cb00e07801e9e9d7e96852ddd3">sf::Vector3&lt; T &gt;</a>
</li>
<li>operator+=()
: <a class="el" href="classsf_1_1Color.php#af39790b2e677c9ab418787f5ff4583ef">sf::Color</a>
, <a class="el" href="classsf_1_1String.php#ae6563ce2c243ae2160eea8a354199f4e">sf::String</a>
, <a class="el" href="classsf_1_1Time.php#a34b983deefecaf2725131771d54631e0">sf::Time</a>
, <a class="el" href="classsf_1_1Vector2.php#ad4b7a9d355d57790bfc7df0ade8bb628">sf::Vector2&lt; T &gt;</a>
, <a class="el" href="classsf_1_1Vector3.php#abc28859af163c63318ea2723b81c5ad9">sf::Vector3&lt; T &gt;</a>
</li>
<li>operator-()
: <a class="el" href="classsf_1_1Color.php#a4586e31d668f183fc46576511169bf2c">sf::Color</a>
, <a class="el" href="classsf_1_1Time.php#acaead0aa2de9f82a548fcd8208a40f70">sf::Time</a>
, <a class="el" href="classsf_1_1Vector2.php#a3885c2e66dc427cec7eaa178d59d8e8b">sf::Vector2&lt; T &gt;</a>
, <a class="el" href="classsf_1_1Vector3.php#a9b75d2fb9b0f2fd9fe33f8f06f9dda75">sf::Vector3&lt; T &gt;</a>
</li>
<li>operator-=()
: <a class="el" href="classsf_1_1Color.php#a6927a7dba8b0d330f912fefb43b0c148">sf::Color</a>
, <a class="el" href="classsf_1_1Time.php#ae0a16136d024a44bbaa4ca49ac172c8f">sf::Time</a>
, <a class="el" href="classsf_1_1Vector2.php#a30a5a12ad03c9a3a982a0a313bf84e6f">sf::Vector2&lt; T &gt;</a>
, <a class="el" href="classsf_1_1Vector3.php#aa465672d2a4ee5fd354e585cf08d2ab9">sf::Vector3&lt; T &gt;</a>
</li>
<li>operator-&gt;()
: <a class="el" href="classsf_1_1ThreadLocalPtr.php#a752299e2858076ee89c62d4dbfb19245">sf::ThreadLocalPtr&lt; T &gt;</a>
</li>
<li>operator/()
: <a class="el" href="classsf_1_1Time.php#a5f7b24dd13c0068d5cba678e1d5db9a6">sf::Time</a>
, <a class="el" href="classsf_1_1Vector2.php#a7409dd89cb3aad6c3bc6622311107311">sf::Vector2&lt; T &gt;</a>
, <a class="el" href="classsf_1_1Vector3.php#ad4ba4a83de236ddeb92a7b759187e90d">sf::Vector3&lt; T &gt;</a>
</li>
<li>operator/=()
: <a class="el" href="classsf_1_1Time.php#ad513a413be41bc66feb0ff2b29d5f947">sf::Time</a>
, <a class="el" href="classsf_1_1Vector2.php#ac4d293c9dc7954ccfd5e373972f38b03">sf::Vector2&lt; T &gt;</a>
, <a class="el" href="classsf_1_1Vector3.php#a8995a700f9dffccc6dddb3696ae17b64">sf::Vector3&lt; T &gt;</a>
</li>
<li>operator&lt;
: <a class="el" href="classsf_1_1IpAddress.php#a4886da3f195b8c30d415a94a7009fdd7">sf::IpAddress</a>
, <a class="el" href="classsf_1_1String.php#a5158a142e0966685ec7fb4e147b24ef0">sf::String</a>
, <a class="el" href="classsf_1_1Time.php#a3bad89721b8c026e80082a7aa539f244">sf::Time</a>
, <a class="el" href="classsf_1_1VideoMode.php#a54cc77c0b6c4b133e0147a43d6829b13">sf::VideoMode</a>
</li>
<li>operator&lt;&lt;()
: <a class="el" href="classsf_1_1Packet.php#aa5a465ed02ba29d83ecdafb0ac3fff21">sf::Packet</a>
</li>
<li>operator&lt;=()
: <a class="el" href="classsf_1_1String.php#ac1c1bb5dcf02aad3b2c0a1bf74a11cc9">sf::String</a>
, <a class="el" href="classsf_1_1Time.php#aafb9de87ed6047956cd9487ab807371f">sf::Time</a>
, <a class="el" href="classsf_1_1VideoMode.php#aa094b7b9ae4c0194892ebda7b4b9bb37">sf::VideoMode</a>
</li>
<li>operator=()
: <a class="el" href="classsf_1_1Font.php#a232515549846e3172a514d0b47918399">sf::Font</a>
, <a class="el" href="classsf_1_1SocketSelector.php#ae6395c7a8d29a9ea14939cc5d1ba3a33">sf::SocketSelector</a>
, <a class="el" href="classsf_1_1Sound.php#a08c64c9c1dabeebc59fbf2540d81d4dd">sf::Sound</a>
, <a class="el" href="classsf_1_1SoundBuffer.php#adcc786b60bbd95be1551368fafd274a7">sf::SoundBuffer</a>
, <a class="el" href="classsf_1_1SoundSource.php#a355a07f34b5ecc38465d39a33b701b6d">sf::SoundSource</a>
, <a class="el" href="classsf_1_1String.php#a096255c066e5ef8c31952216b8ce9c42">sf::String</a>
, <a class="el" href="classsf_1_1Texture.php#a80a089b6b19bb09b83012d5f0e6af9ba">sf::Texture</a>
, <a class="el" href="classsf_1_1ThreadLocalPtr.php#a934db0e5bed32b2d8d0cb02786fb91cf">sf::ThreadLocalPtr&lt; T &gt;</a>
, <a class="el" href="classsf_1_1VertexBuffer.php#a812f98083da8f10361d457008bf9fa79">sf::VertexBuffer</a>
</li>
<li>operator==()
: <a class="el" href="structsf_1_1BlendMode.php#a20d1be06061109c3cef58e0cc38729ea">sf::BlendMode</a>
, <a class="el" href="classsf_1_1Color.php#a2adc3f68860f7aa5e4d7c79dcbb31d30">sf::Color</a>
, <a class="el" href="classsf_1_1Rect.php#ab3488b5dbd0e587c4d7cb80605affc46">sf::Rect&lt; T &gt;</a>
, <a class="el" href="classsf_1_1String.php#a483931724196c580552b68751fb4d837">sf::String</a>
, <a class="el" href="classsf_1_1Time.php#a9bbb2368cf012149f1001535a20c664a">sf::Time</a>
, <a class="el" href="classsf_1_1Transform.php#aa2de0a3ee2f8af05dbc94bf3b4633b4a">sf::Transform</a>
, <a class="el" href="classsf_1_1Vector2.php#a9a7b2d36c3850828fdb651facfd25136">sf::Vector2&lt; T &gt;</a>
, <a class="el" href="classsf_1_1Vector3.php#a388d72db973306a35ba467016b3dee30">sf::Vector3&lt; T &gt;</a>
, <a class="el" href="classsf_1_1VideoMode.php#aca24086fd94d11014f3a0b5ca9a3acd6">sf::VideoMode</a>
</li>
<li>operator&gt;()
: <a class="el" href="classsf_1_1String.php#ac96278a8cbe282632b11f0c8c007df0c">sf::String</a>
, <a class="el" href="classsf_1_1Time.php#a9a472ce6d82aa0caf8e20af4a4b309f2">sf::Time</a>
, <a class="el" href="classsf_1_1VideoMode.php#a5b894cab5f2a3a14597e4c6d200179a4">sf::VideoMode</a>
</li>
<li>operator&gt;=()
: <a class="el" href="classsf_1_1String.php#a112689eec28e0ca9489e8c4ec6a34493">sf::String</a>
, <a class="el" href="classsf_1_1Time.php#a158c5f9a6abf575651b7b2f6af8aedaa">sf::Time</a>
, <a class="el" href="classsf_1_1VideoMode.php#a6e3d91683fcabb88c5b640e9884fe3df">sf::VideoMode</a>
</li>
<li>operator&gt;&gt;()
: <a class="el" href="classsf_1_1Packet.php#af8e26c63ba9bdccd262565ff0d3eeba2">sf::Packet</a>
</li>
<li>operator[]()
: <a class="el" href="classsf_1_1String.php#abc989da7f4fb873ab29188d40772ab24">sf::String</a>
, <a class="el" href="classsf_1_1VertexArray.php#a6bfcf91c01c754e86ee8b44b6c79441b">sf::VertexArray</a>
</li>
<li>Orientation
: <a class="el" href="classsf_1_1Sensor.php#a687375af3ab77b818fca73735bcaea84aa428c5260446555de87c69b65f6edf00">sf::Sensor</a>
</li>
<li>OutputSoundFile()
: <a class="el" href="classsf_1_1OutputSoundFile.php#a7ae9f2dbd0991fa9394726a3d58bb19e">sf::OutputSoundFile</a>
</li>
</ul>
</div><!-- contents -->
<?php
    require("../footer.php");
?>
