<?php
    $version = '2.4.1'; // the $ projectnumber variable is automatically replaced by doxygen with the version number
    $pagetitle = 'Class Members - Functions'; // the $ title variable is automatically replaced by doxygen with the page title
    include('../header-fr.php');
?>
<!-- Generated by Doxygen 1.8.12 -->
<script type="text/javascript" src="menudata.js"></script>
<script type="text/javascript" src="menu.js"></script>
<script type="text/javascript">
$(function() {
  initMenu('',false,false,'search.php','Search');
});
</script>
<div id="main-nav"></div>
</div><!-- top -->
<div class="contents">
&#160;

<h3><a id="index_m"></a>- m -</h3><ul>
<li>mapCoordsToPixel()
: <a class="el" href="classsf_1_1RenderTarget.php#ad92a9f0283aa5f3f67e473c1105b68cf">sf::RenderTarget</a>
</li>
<li>mapPixelToCoords()
: <a class="el" href="classsf_1_1RenderTarget.php#a2d3e9d7c4a1f5ea7e52b06f53e3011f9">sf::RenderTarget</a>
</li>
<li>MemoryInputStream()
: <a class="el" href="classsf_1_1MemoryInputStream.php#a2d78851a69a8956a79872be41bcdfe0e">sf::MemoryInputStream</a>
</li>
<li>microseconds()
: <a class="el" href="classsf_1_1Time.php#a8a6ae28a1962198a69b92355649c6aa0">sf::Time</a>
</li>
<li>milliseconds()
: <a class="el" href="classsf_1_1Time.php#a9231f886d925a24d181c8dcfa6448d87">sf::Time</a>
</li>
<li>move()
: <a class="el" href="classsf_1_1Transformable.php#ab9ca691522f6ddc1a40406849b87c469">sf::Transformable</a>
, <a class="el" href="classsf_1_1View.php#a4c98a6e04fed756dfaff8f629de50862">sf::View</a>
</li>
<li>Music()
: <a class="el" href="classsf_1_1Music.php#a0bc787d8e022b3a9b89cf2c28befd42e">sf::Music</a>
</li>
<li>Mutex()
: <a class="el" href="classsf_1_1Mutex.php#a9bd52a48320fd7b6db8a78037aad276e">sf::Mutex</a>
</li>
</ul>
</div><!-- contents -->
<?php
    require("../footer-fr.php");
?>
