<?php
    $version = '2.0'; // the $ projectnumber variable is automatically replaced by doxygen with the version number
    include('../header.php');
?>
<!-- Generated by Doxygen 1.8.2 -->
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="modules.php"><span>Modules</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="classes.php"><span>Class&#160;Index</span></a></li>
      <li><a href="hierarchy.php"><span>Class&#160;Hierarchy</span></a></li>
      <li><a href="functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
</div><!-- top -->
<div class="header">
  <div class="summary">
<a href="#pub-methods">Instance Methods</a> &#124;
<a href="classSilentWindow-members.php">List of all members</a>  </div>
  <div class="headertitle">
<div class="title">SilentWindow Class Reference</div>  </div>
</div><!--header-->
<div class="contents">
<div id="dynsection-0" onclick="return toggleVisibility(this)" class="dynheader closed" style="cursor:pointer;">
  <img id="dynsection-0-trigger" src="closed.png" alt="+"/> Inheritance diagram for SilentWindow:</div>
<div id="dynsection-0-summary" class="dynsummary" style="display:block;">
</div>
<div id="dynsection-0-content" class="dyncontent" style="display:none;">
 <div class="center">
  <img src="interfaceSilentWindow.png" usemap="#SilentWindow_map" alt=""/>
  <map id="SilentWindow_map" name="SilentWindow_map">
</map>
 </div></div>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-methods"></a>
Instance Methods</h2></td></tr>
<tr class="memitem:ac5173b430a1eb708acedfdf80b546dd4"><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ac5173b430a1eb708acedfdf80b546dd4"></a>
(void)&#160;</td><td class="memItemRight" valign="bottom">- <b>keyDown:</b></td></tr>
<tr class="separator:ac5173b430a1eb708acedfdf80b546dd4"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock">
<p>Definition at line <a class="el" href="CocoaAppDelegate_8h_source.php#l00070">70</a> of file <a class="el" href="CocoaAppDelegate_8h_source.php">CocoaAppDelegate.h</a>.</p>
</div><hr/>The documentation for this class was generated from the following file:<ul>
<li><a class="el" href="CocoaAppDelegate_8h_source.php">CocoaAppDelegate.h</a></li>
</ul>
</div><!-- contents -->
<?php
    require("../footer.php");
?>
