<?php
    $version = '2.0'; // the $ projectnumber variable is automatically replaced by doxygen with the version number
    include('../header.php');
?>
<!-- Generated by Doxygen 1.8.2 -->
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="modules.php"><span>Modules</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="classes.php"><span>Class&#160;Index</span></a></li>
      <li><a href="hierarchy.php"><span>Class&#160;Hierarchy</span></a></li>
      <li><a href="functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
</div><!-- top -->
<div class="header">
  <div class="summary">
<a href="#pub-attribs">Public Attributes</a> &#124;
<a href="structjpeg__component__info-members.php">List of all members</a>  </div>
  <div class="headertitle">
<div class="title">jpeg_component_info Struct Reference</div>  </div>
</div><!--header-->
<div class="contents">
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-attribs"></a>
Public Attributes</h2></td></tr>
<tr class="memitem:a205782ff7ec47c58cb470f121247ea8d"><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a205782ff7ec47c58cb470f121247ea8d"></a>
int&#160;</td><td class="memItemRight" valign="bottom"><b>component_id</b></td></tr>
<tr class="separator:a205782ff7ec47c58cb470f121247ea8d"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aa29b9e1c664a9b0b8a1c3069ad167817"><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="aa29b9e1c664a9b0b8a1c3069ad167817"></a>
int&#160;</td><td class="memItemRight" valign="bottom"><b>component_index</b></td></tr>
<tr class="separator:aa29b9e1c664a9b0b8a1c3069ad167817"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a3a8e122fa2eee3c7bede586d371fe202"><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a3a8e122fa2eee3c7bede586d371fe202"></a>
int&#160;</td><td class="memItemRight" valign="bottom"><b>h_samp_factor</b></td></tr>
<tr class="separator:a3a8e122fa2eee3c7bede586d371fe202"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a83b263da2a749a8fe96be728889af0df"><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a83b263da2a749a8fe96be728889af0df"></a>
int&#160;</td><td class="memItemRight" valign="bottom"><b>v_samp_factor</b></td></tr>
<tr class="separator:a83b263da2a749a8fe96be728889af0df"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a0a9d70b6a95d3ca58a34a7ea8bfefbf8"><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a0a9d70b6a95d3ca58a34a7ea8bfefbf8"></a>
int&#160;</td><td class="memItemRight" valign="bottom"><b>quant_tbl_no</b></td></tr>
<tr class="separator:a0a9d70b6a95d3ca58a34a7ea8bfefbf8"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a304fa583caa0601abc7077a218988854"><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a304fa583caa0601abc7077a218988854"></a>
int&#160;</td><td class="memItemRight" valign="bottom"><b>dc_tbl_no</b></td></tr>
<tr class="separator:a304fa583caa0601abc7077a218988854"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:adfea67573a39b232c3d82ac808539a83"><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="adfea67573a39b232c3d82ac808539a83"></a>
int&#160;</td><td class="memItemRight" valign="bottom"><b>ac_tbl_no</b></td></tr>
<tr class="separator:adfea67573a39b232c3d82ac808539a83"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a059454e8192effeabc6eab34e2ad198d"><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a059454e8192effeabc6eab34e2ad198d"></a>
JDIMENSION&#160;</td><td class="memItemRight" valign="bottom"><b>width_in_blocks</b></td></tr>
<tr class="separator:a059454e8192effeabc6eab34e2ad198d"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a3f9218e7590c328bfd88d900f58886f4"><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a3f9218e7590c328bfd88d900f58886f4"></a>
JDIMENSION&#160;</td><td class="memItemRight" valign="bottom"><b>height_in_blocks</b></td></tr>
<tr class="separator:a3f9218e7590c328bfd88d900f58886f4"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a54dc0e1df56d88d3257fef0abfd9fea0"><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a54dc0e1df56d88d3257fef0abfd9fea0"></a>
int&#160;</td><td class="memItemRight" valign="bottom"><b>DCT_h_scaled_size</b></td></tr>
<tr class="separator:a54dc0e1df56d88d3257fef0abfd9fea0"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a8099359745c7887abe9158cf5655b5f3"><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a8099359745c7887abe9158cf5655b5f3"></a>
int&#160;</td><td class="memItemRight" valign="bottom"><b>DCT_v_scaled_size</b></td></tr>
<tr class="separator:a8099359745c7887abe9158cf5655b5f3"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aacbe6c10eca470c8ec331f91be8cccee"><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="aacbe6c10eca470c8ec331f91be8cccee"></a>
JDIMENSION&#160;</td><td class="memItemRight" valign="bottom"><b>downsampled_width</b></td></tr>
<tr class="separator:aacbe6c10eca470c8ec331f91be8cccee"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a019811f4bcc16fe481e0b53f659b281e"><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a019811f4bcc16fe481e0b53f659b281e"></a>
JDIMENSION&#160;</td><td class="memItemRight" valign="bottom"><b>downsampled_height</b></td></tr>
<tr class="separator:a019811f4bcc16fe481e0b53f659b281e"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a8f9efa098849cd087e20d536b05d4798"><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a8f9efa098849cd087e20d536b05d4798"></a>
boolean&#160;</td><td class="memItemRight" valign="bottom"><b>component_needed</b></td></tr>
<tr class="separator:a8f9efa098849cd087e20d536b05d4798"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a82a5bababd81410839aefec8a61878de"><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a82a5bababd81410839aefec8a61878de"></a>
int&#160;</td><td class="memItemRight" valign="bottom"><b>MCU_width</b></td></tr>
<tr class="separator:a82a5bababd81410839aefec8a61878de"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a09baec129e44114d46d5b19dc98b0105"><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a09baec129e44114d46d5b19dc98b0105"></a>
int&#160;</td><td class="memItemRight" valign="bottom"><b>MCU_height</b></td></tr>
<tr class="separator:a09baec129e44114d46d5b19dc98b0105"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ad9b901306395808c7eb338148e30c2cd"><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="ad9b901306395808c7eb338148e30c2cd"></a>
int&#160;</td><td class="memItemRight" valign="bottom"><b>MCU_blocks</b></td></tr>
<tr class="separator:ad9b901306395808c7eb338148e30c2cd"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aca7e52dcd78bb2fe51104e2add9dade5"><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="aca7e52dcd78bb2fe51104e2add9dade5"></a>
int&#160;</td><td class="memItemRight" valign="bottom"><b>MCU_sample_width</b></td></tr>
<tr class="separator:aca7e52dcd78bb2fe51104e2add9dade5"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a440612272e3e9eac0a240fd34cde5bbe"><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a440612272e3e9eac0a240fd34cde5bbe"></a>
int&#160;</td><td class="memItemRight" valign="bottom"><b>last_col_width</b></td></tr>
<tr class="separator:a440612272e3e9eac0a240fd34cde5bbe"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a7d0738ae3647a019722410a2d718f3d3"><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a7d0738ae3647a019722410a2d718f3d3"></a>
int&#160;</td><td class="memItemRight" valign="bottom"><b>last_row_height</b></td></tr>
<tr class="separator:a7d0738ae3647a019722410a2d718f3d3"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:afd551e8e9dbc3f3076c10cd4d391fdac"><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="afd551e8e9dbc3f3076c10cd4d391fdac"></a>
<a class="el" href="structJQUANT__TBL.php">JQUANT_TBL</a> *&#160;</td><td class="memItemRight" valign="bottom"><b>quant_table</b></td></tr>
<tr class="separator:afd551e8e9dbc3f3076c10cd4d391fdac"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a9f68a39fc17561866668c1b9d4a8f238"><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a9f68a39fc17561866668c1b9d4a8f238"></a>
void *&#160;</td><td class="memItemRight" valign="bottom"><b>dct_table</b></td></tr>
<tr class="separator:a9f68a39fc17561866668c1b9d4a8f238"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock">
<p>Definition at line <a class="el" href="jpeglib_8h_source.php#l00125">125</a> of file <a class="el" href="jpeglib_8h_source.php">jpeglib.h</a>.</p>
</div><hr/>The documentation for this struct was generated from the following file:<ul>
<li><a class="el" href="jpeglib_8h_source.php">jpeglib.h</a></li>
</ul>
</div><!-- contents -->
<?php
    require("../footer.php");
?>
