<?php
    $version = '2.0'; // the $ projectnumber variable is automatically replaced by doxygen with the version number
    include('../header.php');
?>
<!-- Generated by Doxygen 1.8.2 -->
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="modules.php"><span>Modules</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="classes.php"><span>Class&#160;Index</span></a></li>
      <li><a href="hierarchy.php"><span>Class&#160;Hierarchy</span></a></li>
      <li><a href="functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
</div><!-- top -->
<div class="header">
  <div class="headertitle">
<div class="title">jpeg_destination_mgr Member List</div>  </div>
</div><!--header-->
<div class="contents">

<p>This is the complete list of members for <a class="el" href="structjpeg__destination__mgr.php">jpeg_destination_mgr</a>, including all inherited members.</p>
<table class="directory">
  <tr bgcolor="#f0f0f0"class="even"><td class="entry"><b>free_in_buffer</b> (defined in <a class="el" href="structjpeg__destination__mgr.php">jpeg_destination_mgr</a>)</td><td class="entry"><a class="el" href="structjpeg__destination__mgr.php">jpeg_destination_mgr</a></td><td class="entry"></td></tr>
  <tr bgcolor="#f0f0f0"><td class="entry"><b>JMETHOD</b>(void, init_destination,(j_compress_ptr cinfo)) (defined in <a class="el" href="structjpeg__destination__mgr.php">jpeg_destination_mgr</a>)</td><td class="entry"><a class="el" href="structjpeg__destination__mgr.php">jpeg_destination_mgr</a></td><td class="entry"></td></tr>
  <tr bgcolor="#f0f0f0"class="even"><td class="entry"><b>JMETHOD</b>(boolean, empty_output_buffer,(j_compress_ptr cinfo)) (defined in <a class="el" href="structjpeg__destination__mgr.php">jpeg_destination_mgr</a>)</td><td class="entry"><a class="el" href="structjpeg__destination__mgr.php">jpeg_destination_mgr</a></td><td class="entry"></td></tr>
  <tr bgcolor="#f0f0f0"><td class="entry"><b>JMETHOD</b>(void, term_destination,(j_compress_ptr cinfo)) (defined in <a class="el" href="structjpeg__destination__mgr.php">jpeg_destination_mgr</a>)</td><td class="entry"><a class="el" href="structjpeg__destination__mgr.php">jpeg_destination_mgr</a></td><td class="entry"></td></tr>
  <tr bgcolor="#f0f0f0"class="even"><td class="entry"><b>next_output_byte</b> (defined in <a class="el" href="structjpeg__destination__mgr.php">jpeg_destination_mgr</a>)</td><td class="entry"><a class="el" href="structjpeg__destination__mgr.php">jpeg_destination_mgr</a></td><td class="entry"></td></tr>
</table></div><!-- contents -->
<?php
    require("../footer.php");
?>
