<?php
    $version = '2.0'; // the $ projectnumber variable is automatically replaced by doxygen with the version number
    include('../header.php');
?>
<!-- Generated by Doxygen 1.8.2 -->
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="modules.php"><span>Modules</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="classes.php"><span>Class&#160;Index</span></a></li>
      <li><a href="hierarchy.php"><span>Class&#160;Hierarchy</span></a></li>
      <li><a href="functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
</div><!-- top -->
<div class="header">
  <div class="summary">
<a href="#pub-attribs">Public Attributes</a> &#124;
<a href="structFT__OutlineGlyphRec__-members.php">List of all members</a>  </div>
  <div class="headertitle">
<div class="title">FT_OutlineGlyphRec_ Struct Reference</div>  </div>
</div><!--header-->
<div class="contents">
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-attribs"></a>
Public Attributes</h2></td></tr>
<tr class="memitem:a71e5a8d5fe69e0cea68c96486dd6713f"><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="a71e5a8d5fe69e0cea68c96486dd6713f"></a>
<a class="el" href="structFT__GlyphRec__.php">FT_GlyphRec</a>&#160;</td><td class="memItemRight" valign="bottom"><b>root</b></td></tr>
<tr class="separator:a71e5a8d5fe69e0cea68c96486dd6713f"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:af1bd473a32fcbc500edcfcf89e3ac8ac"><td class="memItemLeft" align="right" valign="top"><a class="anchor" id="af1bd473a32fcbc500edcfcf89e3ac8ac"></a>
<a class="el" href="structFT__Outline__.php">FT_Outline</a>&#160;</td><td class="memItemRight" valign="bottom"><b>outline</b></td></tr>
<tr class="separator:af1bd473a32fcbc500edcfcf89e3ac8ac"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock">
<p>Definition at line <a class="el" href="ftglyph_8h_source.php#l00208">208</a> of file <a class="el" href="ftglyph_8h_source.php">ftglyph.h</a>.</p>
</div><hr/>The documentation for this struct was generated from the following file:<ul>
<li><a class="el" href="ftglyph_8h_source.php">ftglyph.h</a></li>
</ul>
</div><!-- contents -->
<?php
    require("../footer.php");
?>
