<?php
    $version = '2.0'; // the $ projectnumber variable is automatically replaced by doxygen with the version number
    include('../header.php');
?>
<!-- Generated by Doxygen 1.8.2 -->
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="modules.php"><span>Modules</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="classes.php"><span>Class&#160;Index</span></a></li>
      <li><a href="hierarchy.php"><span>Class&#160;Hierarchy</span></a></li>
      <li><a href="functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
</div><!-- top -->
<div class="header">
  <div class="headertitle">
<div class="title">FT_FaceRec_ Member List</div>  </div>
</div><!--header-->
<div class="contents">

<p>This is the complete list of members for <a class="el" href="structFT__FaceRec__.php">FT_FaceRec_</a>, including all inherited members.</p>
<table class="directory">
  <tr bgcolor="#f0f0f0"class="even"><td class="entry"><b>ascender</b> (defined in <a class="el" href="structFT__FaceRec__.php">FT_FaceRec_</a>)</td><td class="entry"><a class="el" href="structFT__FaceRec__.php">FT_FaceRec_</a></td><td class="entry"></td></tr>
  <tr bgcolor="#f0f0f0"><td class="entry"><b>autohint</b> (defined in <a class="el" href="structFT__FaceRec__.php">FT_FaceRec_</a>)</td><td class="entry"><a class="el" href="structFT__FaceRec__.php">FT_FaceRec_</a></td><td class="entry"></td></tr>
  <tr bgcolor="#f0f0f0"class="even"><td class="entry"><b>available_sizes</b> (defined in <a class="el" href="structFT__FaceRec__.php">FT_FaceRec_</a>)</td><td class="entry"><a class="el" href="structFT__FaceRec__.php">FT_FaceRec_</a></td><td class="entry"></td></tr>
  <tr bgcolor="#f0f0f0"><td class="entry"><b>bbox</b> (defined in <a class="el" href="structFT__FaceRec__.php">FT_FaceRec_</a>)</td><td class="entry"><a class="el" href="structFT__FaceRec__.php">FT_FaceRec_</a></td><td class="entry"></td></tr>
  <tr bgcolor="#f0f0f0"class="even"><td class="entry"><b>charmap</b> (defined in <a class="el" href="structFT__FaceRec__.php">FT_FaceRec_</a>)</td><td class="entry"><a class="el" href="structFT__FaceRec__.php">FT_FaceRec_</a></td><td class="entry"></td></tr>
  <tr bgcolor="#f0f0f0"><td class="entry"><b>charmaps</b> (defined in <a class="el" href="structFT__FaceRec__.php">FT_FaceRec_</a>)</td><td class="entry"><a class="el" href="structFT__FaceRec__.php">FT_FaceRec_</a></td><td class="entry"></td></tr>
  <tr bgcolor="#f0f0f0"class="even"><td class="entry"><b>descender</b> (defined in <a class="el" href="structFT__FaceRec__.php">FT_FaceRec_</a>)</td><td class="entry"><a class="el" href="structFT__FaceRec__.php">FT_FaceRec_</a></td><td class="entry"></td></tr>
  <tr bgcolor="#f0f0f0"><td class="entry"><b>driver</b> (defined in <a class="el" href="structFT__FaceRec__.php">FT_FaceRec_</a>)</td><td class="entry"><a class="el" href="structFT__FaceRec__.php">FT_FaceRec_</a></td><td class="entry"></td></tr>
  <tr bgcolor="#f0f0f0"class="even"><td class="entry"><b>extensions</b> (defined in <a class="el" href="structFT__FaceRec__.php">FT_FaceRec_</a>)</td><td class="entry"><a class="el" href="structFT__FaceRec__.php">FT_FaceRec_</a></td><td class="entry"></td></tr>
  <tr bgcolor="#f0f0f0"><td class="entry"><b>face_flags</b> (defined in <a class="el" href="structFT__FaceRec__.php">FT_FaceRec_</a>)</td><td class="entry"><a class="el" href="structFT__FaceRec__.php">FT_FaceRec_</a></td><td class="entry"></td></tr>
  <tr bgcolor="#f0f0f0"class="even"><td class="entry"><b>face_index</b> (defined in <a class="el" href="structFT__FaceRec__.php">FT_FaceRec_</a>)</td><td class="entry"><a class="el" href="structFT__FaceRec__.php">FT_FaceRec_</a></td><td class="entry"></td></tr>
  <tr bgcolor="#f0f0f0"><td class="entry"><b>family_name</b> (defined in <a class="el" href="structFT__FaceRec__.php">FT_FaceRec_</a>)</td><td class="entry"><a class="el" href="structFT__FaceRec__.php">FT_FaceRec_</a></td><td class="entry"></td></tr>
  <tr bgcolor="#f0f0f0"class="even"><td class="entry"><b>generic</b> (defined in <a class="el" href="structFT__FaceRec__.php">FT_FaceRec_</a>)</td><td class="entry"><a class="el" href="structFT__FaceRec__.php">FT_FaceRec_</a></td><td class="entry"></td></tr>
  <tr bgcolor="#f0f0f0"><td class="entry"><b>glyph</b> (defined in <a class="el" href="structFT__FaceRec__.php">FT_FaceRec_</a>)</td><td class="entry"><a class="el" href="structFT__FaceRec__.php">FT_FaceRec_</a></td><td class="entry"></td></tr>
  <tr bgcolor="#f0f0f0"class="even"><td class="entry"><b>height</b> (defined in <a class="el" href="structFT__FaceRec__.php">FT_FaceRec_</a>)</td><td class="entry"><a class="el" href="structFT__FaceRec__.php">FT_FaceRec_</a></td><td class="entry"></td></tr>
  <tr bgcolor="#f0f0f0"><td class="entry"><b>internal</b> (defined in <a class="el" href="structFT__FaceRec__.php">FT_FaceRec_</a>)</td><td class="entry"><a class="el" href="structFT__FaceRec__.php">FT_FaceRec_</a></td><td class="entry"></td></tr>
  <tr bgcolor="#f0f0f0"class="even"><td class="entry"><b>max_advance_height</b> (defined in <a class="el" href="structFT__FaceRec__.php">FT_FaceRec_</a>)</td><td class="entry"><a class="el" href="structFT__FaceRec__.php">FT_FaceRec_</a></td><td class="entry"></td></tr>
  <tr bgcolor="#f0f0f0"><td class="entry"><b>max_advance_width</b> (defined in <a class="el" href="structFT__FaceRec__.php">FT_FaceRec_</a>)</td><td class="entry"><a class="el" href="structFT__FaceRec__.php">FT_FaceRec_</a></td><td class="entry"></td></tr>
  <tr bgcolor="#f0f0f0"class="even"><td class="entry"><b>memory</b> (defined in <a class="el" href="structFT__FaceRec__.php">FT_FaceRec_</a>)</td><td class="entry"><a class="el" href="structFT__FaceRec__.php">FT_FaceRec_</a></td><td class="entry"></td></tr>
  <tr bgcolor="#f0f0f0"><td class="entry"><b>num_charmaps</b> (defined in <a class="el" href="structFT__FaceRec__.php">FT_FaceRec_</a>)</td><td class="entry"><a class="el" href="structFT__FaceRec__.php">FT_FaceRec_</a></td><td class="entry"></td></tr>
  <tr bgcolor="#f0f0f0"class="even"><td class="entry"><b>num_faces</b> (defined in <a class="el" href="structFT__FaceRec__.php">FT_FaceRec_</a>)</td><td class="entry"><a class="el" href="structFT__FaceRec__.php">FT_FaceRec_</a></td><td class="entry"></td></tr>
  <tr bgcolor="#f0f0f0"><td class="entry"><b>num_fixed_sizes</b> (defined in <a class="el" href="structFT__FaceRec__.php">FT_FaceRec_</a>)</td><td class="entry"><a class="el" href="structFT__FaceRec__.php">FT_FaceRec_</a></td><td class="entry"></td></tr>
  <tr bgcolor="#f0f0f0"class="even"><td class="entry"><b>num_glyphs</b> (defined in <a class="el" href="structFT__FaceRec__.php">FT_FaceRec_</a>)</td><td class="entry"><a class="el" href="structFT__FaceRec__.php">FT_FaceRec_</a></td><td class="entry"></td></tr>
  <tr bgcolor="#f0f0f0"><td class="entry"><b>size</b> (defined in <a class="el" href="structFT__FaceRec__.php">FT_FaceRec_</a>)</td><td class="entry"><a class="el" href="structFT__FaceRec__.php">FT_FaceRec_</a></td><td class="entry"></td></tr>
  <tr bgcolor="#f0f0f0"class="even"><td class="entry"><b>sizes_list</b> (defined in <a class="el" href="structFT__FaceRec__.php">FT_FaceRec_</a>)</td><td class="entry"><a class="el" href="structFT__FaceRec__.php">FT_FaceRec_</a></td><td class="entry"></td></tr>
  <tr bgcolor="#f0f0f0"><td class="entry"><b>stream</b> (defined in <a class="el" href="structFT__FaceRec__.php">FT_FaceRec_</a>)</td><td class="entry"><a class="el" href="structFT__FaceRec__.php">FT_FaceRec_</a></td><td class="entry"></td></tr>
  <tr bgcolor="#f0f0f0"class="even"><td class="entry"><b>style_flags</b> (defined in <a class="el" href="structFT__FaceRec__.php">FT_FaceRec_</a>)</td><td class="entry"><a class="el" href="structFT__FaceRec__.php">FT_FaceRec_</a></td><td class="entry"></td></tr>
  <tr bgcolor="#f0f0f0"><td class="entry"><b>style_name</b> (defined in <a class="el" href="structFT__FaceRec__.php">FT_FaceRec_</a>)</td><td class="entry"><a class="el" href="structFT__FaceRec__.php">FT_FaceRec_</a></td><td class="entry"></td></tr>
  <tr bgcolor="#f0f0f0"class="even"><td class="entry"><b>underline_position</b> (defined in <a class="el" href="structFT__FaceRec__.php">FT_FaceRec_</a>)</td><td class="entry"><a class="el" href="structFT__FaceRec__.php">FT_FaceRec_</a></td><td class="entry"></td></tr>
  <tr bgcolor="#f0f0f0"><td class="entry"><b>underline_thickness</b> (defined in <a class="el" href="structFT__FaceRec__.php">FT_FaceRec_</a>)</td><td class="entry"><a class="el" href="structFT__FaceRec__.php">FT_FaceRec_</a></td><td class="entry"></td></tr>
  <tr bgcolor="#f0f0f0"class="even"><td class="entry"><b>units_per_EM</b> (defined in <a class="el" href="structFT__FaceRec__.php">FT_FaceRec_</a>)</td><td class="entry"><a class="el" href="structFT__FaceRec__.php">FT_FaceRec_</a></td><td class="entry"></td></tr>
</table></div><!-- contents -->
<?php
    require("../footer.php");
?>
