<?php
    $version = '2.0'; // the $ projectnumber variable is automatically replaced by doxygen with the version number
    include('../header.php');
?>
<!-- Generated by Doxygen 1.8.2 -->
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="modules.php"><span>Modules</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li><a href="annotated.php"><span>Classes</span></a></li>
      <li class="current"><a href="files.php"><span>Files</span></a></li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="files.php"><span>File&#160;List</span></a></li>
      <li><a href="globals.php"><span>File&#160;Members</span></a></li>
    </ul>
  </div>
<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="dir_83ae1a5e8455fc62607b4936b42116e9.php">sfml</a></li><li class="navelem"><a class="el" href="dir_79a044fa5ec8bbf4af7d440d8995a178.php">sfml</a></li><li class="navelem"><a class="el" href="dir_f3190241575fd2bd132a392ae6942f4a.php">include</a></li><li class="navelem"><a class="el" href="dir_692f376662c82a26cfe4cfa3aceebe24.php">SFML</a></li><li class="navelem"><a class="el" href="dir_60c5c649f8df3b69a45a020d59f81335.php">System</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="summary">
<a href="#nested-classes">Classes</a> &#124;
<a href="#namespaces">Namespaces</a> &#124;
<a href="#typedef-members">Typedefs</a>  </div>
  <div class="headertitle">
<div class="title">Utf.hpp File Reference</div>  </div>
</div><!--header-->
<div class="contents">
<div class="textblock"><code>#include &lt;<a class="el" href="Config_8hpp_source.php">SFML/Config.hpp</a>&gt;</code><br/>
<code>#include &lt;algorithm&gt;</code><br/>
<code>#include &lt;locale&gt;</code><br/>
<code>#include &lt;string&gt;</code><br/>
<code>#include &lt;cstdlib&gt;</code><br/>
<code>#include &lt;SFML/System/Utf.inl&gt;</code><br/>
</div>
<p><a href="Utf_8hpp_source.php">Go to the source code of this file.</a></p>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="nested-classes"></a>
Classes</h2></td></tr>
<tr class="memitem:"><td class="memItemLeft" align="right" valign="top">class &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classUtf.php">Utf&lt; N &gt;</a></td></tr>
<tr class="separator:"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:"><td class="memItemLeft" align="right" valign="top">class &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classsf_1_1Utf_3_018_01_4.php">sf::Utf&lt; 8 &gt;</a></td></tr>
<tr class="memdesc:"><td class="mdescLeft">&#160;</td><td class="mdescRight">Specialization of the <a class="el" href="classsf_1_1Utf.php" title="Utility class providing generic functions for UTF conversions.">Utf</a> template for UTF-8.  <a href="classsf_1_1Utf_3_018_01_4.php#details">More...</a><br/></td></tr>
<tr class="separator:"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:"><td class="memItemLeft" align="right" valign="top">class &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classsf_1_1Utf_3_0116_01_4.php">sf::Utf&lt; 16 &gt;</a></td></tr>
<tr class="memdesc:"><td class="mdescLeft">&#160;</td><td class="mdescRight">Specialization of the <a class="el" href="classsf_1_1Utf.php" title="Utility class providing generic functions for UTF conversions.">Utf</a> template for UTF-16.  <a href="classsf_1_1Utf_3_0116_01_4.php#details">More...</a><br/></td></tr>
<tr class="separator:"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:"><td class="memItemLeft" align="right" valign="top">class &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classsf_1_1Utf_3_0132_01_4.php">sf::Utf&lt; 32 &gt;</a></td></tr>
<tr class="memdesc:"><td class="mdescLeft">&#160;</td><td class="mdescRight">Specialization of the <a class="el" href="classsf_1_1Utf.php" title="Utility class providing generic functions for UTF conversions.">Utf</a> template for UTF-32.  <a href="classsf_1_1Utf_3_0132_01_4.php#details">More...</a><br/></td></tr>
<tr class="separator:"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="namespaces"></a>
Namespaces</h2></td></tr>
<tr class="memitem:namespacesf"><td class="memItemLeft" align="right" valign="top">namespace &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="namespacesf.php">sf</a></td></tr>
<tr class="separator:"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="typedef-members"></a>
Typedefs</h2></td></tr>
<tr class="memitem:ab78b7f576a82034d14eab92becc15301"><td class="memItemLeft" align="right" valign="top">typedef <a class="el" href="classUtf.php">Utf</a>&lt; 8 &gt;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="namespacesf.php#ab78b7f576a82034d14eab92becc15301">sf::Utf8</a></td></tr>
<tr class="separator:ab78b7f576a82034d14eab92becc15301"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ae30b6ea05a1723d608853ebc3043e53d"><td class="memItemLeft" align="right" valign="top">typedef <a class="el" href="classUtf.php">Utf</a>&lt; 16 &gt;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="namespacesf.php#ae30b6ea05a1723d608853ebc3043e53d">sf::Utf16</a></td></tr>
<tr class="separator:ae30b6ea05a1723d608853ebc3043e53d"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a51a40f697607908d2e9f58e67f4c89a3"><td class="memItemLeft" align="right" valign="top">typedef <a class="el" href="classUtf.php">Utf</a>&lt; 32 &gt;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="namespacesf.php#a51a40f697607908d2e9f58e67f4c89a3">sf::Utf32</a></td></tr>
<tr class="separator:a51a40f697607908d2e9f58e67f4c89a3"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
</div><!-- contents -->
<?php
    require("../footer.php");
?>
