<?php
    $version = '2.6.0'; // the $ projectnumber variable is automatically replaced by doxygen with the version number
    $pagetitle = 'Class Members - Functions'; // the $ title variable is automatically replaced by doxygen with the page title
    include('../header.php');
?>
<!-- Generated by Doxygen 1.9.6 -->
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:d3d9a9a6595521f9666a5e94cc830dab83b65699&amp;dn=expat.txt MIT */
var searchBox = new SearchBox("searchBox", "search/",'.php');
/* @license-end */
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="pages.php"><span>Related&#160;Pages</span></a></li>
      <li><a href="modules.php"><span>Modules</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <span id="MSearchSelect"                onmouseover="return searchBox.OnSearchSelectShow()"                onmouseout="return searchBox.OnSearchSelectHide()">&#160;</span>
          <input type="text" id="MSearchField" value="" placeholder="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.svg" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="classes.php"><span>Class&#160;Index</span></a></li>
      <li><a href="hierarchy.php"><span>Class&#160;Hierarchy</span></a></li>
      <li class="current"><a href="functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
  <div id="navrow3" class="tabs2">
    <ul class="tablist">
      <li><a href="functions.php"><span>All</span></a></li>
      <li class="current"><a href="functions_func.php"><span>Functions</span></a></li>
      <li><a href="functions_vars.php"><span>Variables</span></a></li>
      <li><a href="functions_type.php"><span>Typedefs</span></a></li>
      <li><a href="functions_enum.php"><span>Enumerations</span></a></li>
      <li><a href="functions_eval.php"><span>Enumerator</span></a></li>
      <li><a href="functions_rela.php"><span>Related&#160;Functions</span></a></li>
    </ul>
  </div>
  <div id="navrow4" class="tabs3">
    <ul class="tablist">
      <li><a href="functions_func.php#index_a"><span>a</span></a></li>
      <li><a href="functions_func_b.php#index_b"><span>b</span></a></li>
      <li><a href="functions_func_c.php#index_c"><span>c</span></a></li>
      <li><a href="functions_func_d.php#index_d"><span>d</span></a></li>
      <li><a href="functions_func_e.php#index_e"><span>e</span></a></li>
      <li><a href="functions_func_f.php#index_f"><span>f</span></a></li>
      <li><a href="functions_func_g.php#index_g"><span>g</span></a></li>
      <li><a href="functions_func_h.php#index_h"><span>h</span></a></li>
      <li><a href="functions_func_i.php#index_i"><span>i</span></a></li>
      <li><a href="functions_func_k.php#index_k"><span>k</span></a></li>
      <li><a href="functions_func_l.php#index_l"><span>l</span></a></li>
      <li><a href="functions_func_m.php#index_m"><span>m</span></a></li>
      <li><a href="functions_func_n.php#index_n"><span>n</span></a></li>
      <li><a href="functions_func_o.php#index_o"><span>o</span></a></li>
      <li><a href="functions_func_p.php#index_p"><span>p</span></a></li>
      <li class="current"><a href="functions_func_r.php#index_r"><span>r</span></a></li>
      <li><a href="functions_func_s.php#index_s"><span>s</span></a></li>
      <li><a href="functions_func_t.php#index_t"><span>t</span></a></li>
      <li><a href="functions_func_u.php#index_u"><span>u</span></a></li>
      <li><a href="functions_func_v.php#index_v"><span>v</span></a></li>
      <li><a href="functions_func_w.php#index_w"><span>w</span></a></li>
      <li><a href="functions_func_z.php#index_z"><span>z</span></a></li>
      <li><a href="functions_func_~.php#index__7E"><span>~</span></a></li>
    </ul>
  </div>
</div><!-- top -->
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<div id="MSearchResults">
<div class="SRPage">
<div id="SRIndex">
<div id="SRResults"></div>
<div class="SRStatus" id="Loading">Loading...</div>
<div class="SRStatus" id="Searching">Searching...</div>
<div class="SRStatus" id="NoMatches">No Matches</div>
</div>
</div>
</div>
</div>

<div class="contents">
&#160;

<h3><a id="index_r" name="index_r"></a>- r -</h3><ul>
<li>read()&#160;:&#160;<a class="el" href="classsf_1_1FileInputStream.php#ad1e94c4152429f485db224c44ee1eb50">sf::FileInputStream</a>, <a class="el" href="classsf_1_1InputSoundFile.php#a83d6f64617456601edeb0daf9d14a17f">sf::InputSoundFile</a>, <a class="el" href="classsf_1_1InputStream.php#a8dd89c74c1acb693203f50e750c6ae53">sf::InputStream</a>, <a class="el" href="classsf_1_1MemoryInputStream.php#adff5270c521819639154d42d76fd4c34">sf::MemoryInputStream</a>, <a class="el" href="classsf_1_1SoundFileReader.php#a3b7d86769ea07e24e7b0f0486bed7591">sf::SoundFileReader</a></li>
<li>receive()&#160;:&#160;<a class="el" href="classsf_1_1TcpSocket.php#a90ce50811ea61d4f00efc62bb99ae1af">sf::TcpSocket</a>, <a class="el" href="classsf_1_1UdpSocket.php#ade9ca0f7ed7919136917b0b997a9833a">sf::UdpSocket</a></li>
<li>Rect()&#160;:&#160;<a class="el" href="classsf_1_1Rect.php#a0f87ebaef9722a6222fd2e04ce8efb37">sf::Rect&lt; T &gt;</a></li>
<li>RectangleShape()&#160;:&#160;<a class="el" href="classsf_1_1RectangleShape.php#a83a2be157ebee85c95ed491c3e78dd7c">sf::RectangleShape</a></li>
<li>registerContextDestroyCallback()&#160;:&#160;<a class="el" href="classsf_1_1GlResource.php#ab171bdaf5eb36789da14b30a846db471">sf::GlResource</a></li>
<li>registerReader()&#160;:&#160;<a class="el" href="classsf_1_1SoundFileFactory.php#aeee396bfdbb6ac24c57e5c73c30ec105">sf::SoundFileFactory</a></li>
<li>registerWriter()&#160;:&#160;<a class="el" href="classsf_1_1SoundFileFactory.php#abb6e082ea3fedf22c8648113d1be5755">sf::SoundFileFactory</a></li>
<li>remove()&#160;:&#160;<a class="el" href="classsf_1_1SocketSelector.php#a98b6ab693a65b82caa375639232357c1">sf::SocketSelector</a></li>
<li>renameFile()&#160;:&#160;<a class="el" href="classsf_1_1Ftp.php#a8f99251d7153e1dc26723e4006deb764">sf::Ftp</a></li>
<li>RenderStates()&#160;:&#160;<a class="el" href="classsf_1_1RenderStates.php#a885bf14070d0d5391f062f62b270b7d0">sf::RenderStates</a></li>
<li>RenderTarget()&#160;:&#160;<a class="el" href="classsf_1_1RenderTarget.php#a2997c96cbd93cb8ce0aba2ddae35b86f">sf::RenderTarget</a></li>
<li>RenderTexture()&#160;:&#160;<a class="el" href="classsf_1_1RenderTexture.php#a19ee6e5b4c40ad251803389b3953a9c6">sf::RenderTexture</a></li>
<li>RenderWindow()&#160;:&#160;<a class="el" href="classsf_1_1RenderWindow.php#a839bbf336bdcafb084dafc3076fc9021">sf::RenderWindow</a></li>
<li>replace()&#160;:&#160;<a class="el" href="classsf_1_1String.php#ad460e628c287b0fa88deba2eb0b6744b">sf::String</a></li>
<li>Request()&#160;:&#160;<a class="el" href="classsf_1_1Http_1_1Request.php#a8e89d9e8ffcc1163259b35d79809a61c">sf::Http::Request</a></li>
<li>requestFocus()&#160;:&#160;<a class="el" href="classsf_1_1WindowBase.php#a448770d2372d8df0a1ad6b1c7cce3c89">sf::WindowBase</a></li>
<li>reset()&#160;:&#160;<a class="el" href="classsf_1_1View.php#ac95b636eafab3922b7e8304fb6c00d7d">sf::View</a></li>
<li>resetBuffer()&#160;:&#160;<a class="el" href="classsf_1_1Sound.php#acb7289d45e06fb76b8292ac84beb82a7">sf::Sound</a></li>
<li>resetGLStates()&#160;:&#160;<a class="el" href="classsf_1_1RenderTarget.php#aac7504990d27dada4bfe3c7866920765">sf::RenderTarget</a></li>
<li>resize()&#160;:&#160;<a class="el" href="classsf_1_1VertexArray.php#a0c0fe239e8f9a54e64d3bbc96bf548c0">sf::VertexArray</a></li>
<li>Response()&#160;:&#160;<a class="el" href="classsf_1_1Ftp_1_1Response.php#af300fffd4862774102f978eb22f85d9b">sf::Ftp::Response</a>, <a class="el" href="classsf_1_1Http_1_1Response.php#a2e51c89356fe6a007c448a841a9ec08c">sf::Http::Response</a></li>
<li>restart()&#160;:&#160;<a class="el" href="classsf_1_1Clock.php#a123e2627f2943e5ecaa1db0c7df3231b">sf::Clock</a></li>
<li>rotate()&#160;:&#160;<a class="el" href="classsf_1_1Transform.php#ad09ce22a1fb08709f66f30befc7b2e7b">sf::Transform</a>, <a class="el" href="classsf_1_1Transformable.php#af8a5ffddc0d93f238fee3bf8efe1ebda">sf::Transformable</a>, <a class="el" href="classsf_1_1View.php#a5fd3901aae1845586ca40add94faa378">sf::View</a></li>
</ul>
</div><!-- contents -->
<?php
    require("../footer.php");
?>
