<?php
    $version = '2.4.2'; // the $ projectnumber variable is automatically replaced by doxygen with the version number
    $pagetitle = 'Member List'; // the $ title variable is automatically replaced by doxygen with the page title
    include('../header-fr.php');
?>
<!-- Generated by Doxygen 1.8.10 -->
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="pages.php"><span>Related&#160;Pages</span></a></li>
      <li><a href="modules.php"><span>Modules</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="classes.php"><span>Class&#160;Index</span></a></li>
      <li><a href="hierarchy.php"><span>Class&#160;Hierarchy</span></a></li>
      <li><a href="functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><b>sf</b></li><li class="navelem"><a class="el" href="classsf_1_1TcpListener.php">TcpListener</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="headertitle">
<div class="title">sf::TcpListener Member List</div>  </div>
</div><!--header-->
<div class="contents">

<p>This is the complete list of members for <a class="el" href="classsf_1_1TcpListener.php">sf::TcpListener</a>, including all inherited members.</p>
<table class="directory">
  <tr class="even"><td class="entry"><a class="el" href="classsf_1_1TcpListener.php#ae2c83ce5a64d50b68180c46bef0a7346">accept</a>(TcpSocket &amp;socket)</td><td class="entry"><a class="el" href="classsf_1_1TcpListener.php">sf::TcpListener</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="classsf_1_1Socket.php#a5deb2c955fd347259c3a20d27b2481aaa5a3c30fd128895403afc11076f461b19">AnyPort</a> enum value</td><td class="entry"><a class="el" href="classsf_1_1Socket.php">sf::Socket</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="classsf_1_1TcpListener.php#a3a00a850506bd0f9f48867a0fe59556b">close</a>()</td><td class="entry"><a class="el" href="classsf_1_1TcpListener.php">sf::TcpListener</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="classsf_1_1Socket.php#aafbe140f4b1921e0d19e88cf7a61dcbc">create</a>()</td><td class="entry"><a class="el" href="classsf_1_1Socket.php">sf::Socket</a></td><td class="entry"><span class="mlabel">protected</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="classsf_1_1Socket.php#af1dd898f7aa3ead7ff7b2d1c20e97781">create</a>(SocketHandle handle)</td><td class="entry"><a class="el" href="classsf_1_1Socket.php">sf::Socket</a></td><td class="entry"><span class="mlabel">protected</span></td></tr>
  <tr><td class="entry"><a class="el" href="classsf_1_1Socket.php#a51bf0fd51057b98a10fbb866246176dcab215141f756acdc23c67fad149710eb1">Disconnected</a> enum value</td><td class="entry"><a class="el" href="classsf_1_1Socket.php">sf::Socket</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="classsf_1_1Socket.php#a51bf0fd51057b98a10fbb866246176dca1de3a85bc56d3ae85b3d0f3cfd04ae90">Done</a> enum value</td><td class="entry"><a class="el" href="classsf_1_1Socket.php">sf::Socket</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="classsf_1_1Socket.php#a51bf0fd51057b98a10fbb866246176dca1dc9854433a28c22e192721179a2df5d">Error</a> enum value</td><td class="entry"><a class="el" href="classsf_1_1Socket.php">sf::Socket</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="classsf_1_1Socket.php#ac0c63b13e61da8294bf54e888e97f9a3">getHandle</a>() const </td><td class="entry"><a class="el" href="classsf_1_1Socket.php">sf::Socket</a></td><td class="entry"><span class="mlabel">protected</span></td></tr>
  <tr><td class="entry"><a class="el" href="classsf_1_1TcpListener.php#a3bb62b92684cd1a14b14efdaf0471440">getLocalPort</a>() const </td><td class="entry"><a class="el" href="classsf_1_1TcpListener.php">sf::TcpListener</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="classsf_1_1Socket.php#a0ec0d831b015e32eb5935fd2a9f8c67c">isBlocking</a>() const </td><td class="entry"><a class="el" href="classsf_1_1Socket.php">sf::Socket</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="classsf_1_1TcpListener.php#a9504758ea3570e62cb20b209c11776a1">listen</a>(unsigned short port, const IpAddress &amp;address=IpAddress::Any)</td><td class="entry"><a class="el" href="classsf_1_1TcpListener.php">sf::TcpListener</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="classsf_1_1Socket.php#a51bf0fd51057b98a10fbb866246176dca8554848daae98f996e131bdeed076c09">NotReady</a> enum value</td><td class="entry"><a class="el" href="classsf_1_1Socket.php">sf::Socket</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="classsf_1_1Socket.php#a51bf0fd51057b98a10fbb866246176dca181c163fad2eaea927185d127c392706">Partial</a> enum value</td><td class="entry"><a class="el" href="classsf_1_1Socket.php">sf::Socket</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="classsf_1_1Socket.php#a165fc1423e281ea2714c70303d3a9782">setBlocking</a>(bool blocking)</td><td class="entry"><a class="el" href="classsf_1_1Socket.php">sf::Socket</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="classsf_1_1Socket.php#a80ffb47ec0bafc83af019055d3e6a303">Socket</a>(Type type)</td><td class="entry"><a class="el" href="classsf_1_1Socket.php">sf::Socket</a></td><td class="entry"><span class="mlabel">protected</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="classsf_1_1Socket.php#a51bf0fd51057b98a10fbb866246176dc">Status</a> enum name</td><td class="entry"><a class="el" href="classsf_1_1Socket.php">sf::Socket</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="classsf_1_1Socket.php#a5d3ff44e56e68f02816bb0fabc34adf8acc02e97e90234b957eaad4dff7f22214">Tcp</a> enum value</td><td class="entry"><a class="el" href="classsf_1_1Socket.php">sf::Socket</a></td><td class="entry"><span class="mlabel">protected</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="classsf_1_1TcpListener.php#a59a1db5b6f4711a3e57390da2f8d9630">TcpListener</a>()</td><td class="entry"><a class="el" href="classsf_1_1TcpListener.php">sf::TcpListener</a></td><td class="entry"></td></tr>
  <tr><td class="entry"><a class="el" href="classsf_1_1Socket.php#a5d3ff44e56e68f02816bb0fabc34adf8">Type</a> enum name</td><td class="entry"><a class="el" href="classsf_1_1Socket.php">sf::Socket</a></td><td class="entry"><span class="mlabel">protected</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="classsf_1_1Socket.php#a5d3ff44e56e68f02816bb0fabc34adf8a6ebf3094830db4820191a327f3cc6ce2">Udp</a> enum value</td><td class="entry"><a class="el" href="classsf_1_1Socket.php">sf::Socket</a></td><td class="entry"><span class="mlabel">protected</span></td></tr>
  <tr><td class="entry"><a class="el" href="classsf_1_1Socket.php#a79a4b5918f0b34a2f8db449089694788">~Socket</a>()</td><td class="entry"><a class="el" href="classsf_1_1Socket.php">sf::Socket</a></td><td class="entry"><span class="mlabel">virtual</span></td></tr>
</table></div><!-- contents -->
<?php
    require("../footer-fr.php");
?>
