<?php
    $version = '2.4.1'; // the $ projectnumber variable is automatically replaced by doxygen with the version number
    $pagetitle = 'sf::Ftp::ListingResponse Class Reference'; // the $ title variable is automatically replaced by doxygen with the page title
    include('../header-fr.php');
?>
<!-- Generated by Doxygen 1.8.10 -->
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="pages.php"><span>Related&#160;Pages</span></a></li>
      <li><a href="modules.php"><span>Modules</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="classes.php"><span>Class&#160;Index</span></a></li>
      <li><a href="hierarchy.php"><span>Class&#160;Hierarchy</span></a></li>
      <li><a href="functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><b>sf</b></li><li class="navelem"><a class="el" href="classsf_1_1Ftp.php">Ftp</a></li><li class="navelem"><a class="el" href="classsf_1_1Ftp_1_1ListingResponse.php">ListingResponse</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="summary">
<a href="#pub-types">Public Types</a> &#124;
<a href="#pub-methods">Public Member Functions</a> &#124;
<a href="classsf_1_1Ftp_1_1ListingResponse-members.php">List of all members</a>  </div>
  <div class="headertitle">
<div class="title">sf::Ftp::ListingResponse Class Reference</div>  </div>
</div><!--header-->
<div class="contents">

<p>Specialization of FTP response returning a filename listing.  
 <a href="classsf_1_1Ftp_1_1ListingResponse.php#details">More...</a></p>

<p><code>#include &lt;<a class="el" href="include_2SFML_2Network_2Ftp_8hpp_source.php">Ftp.hpp</a>&gt;</code></p>
<div class="dynheader">
Inheritance diagram for sf::Ftp::ListingResponse:</div>
<div class="dyncontent">
 <div class="center">
  <img src="classsf_1_1Ftp_1_1ListingResponse.png" usemap="#sf::Ftp::ListingResponse_map" alt=""/>
  <map id="sf::Ftp::ListingResponse_map" name="sf::Ftp::ListingResponse_map">
<area href="classsf_1_1Ftp_1_1Response.php" title="Define a FTP response. " alt="sf::Ftp::Response" shape="rect" coords="0,0,143,24"/>
<area href="classsf_1_1Ftp_1_1Response.php" title="Define a FTP response. " alt="sf::Ftp::Response" shape="rect" coords="153,0,296,24"/>
</map>
 </div></div>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-types"></a>
Public Types</h2></td></tr>
<tr class="memitem:af81738f06b6f571761696291276acb3b"><td class="memItemLeft" align="right" valign="top">enum &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3b">Status</a> { <br />
&#160;&#160;<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3ba9c0f2a9ad7404aa610eb835ba06724a4">RestartMarkerReply</a> = 110, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3ba68f0497585e490250bc2985edb4201d3">ServiceReadySoon</a> = 120, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3bac40df58b564d1256c9dc7cbdaede9ad2">DataConnectionAlreadyOpened</a> = 125, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3bab31a5cb621b4097247dfd59565ae8b98">OpeningDataConnection</a> = 150, 
<br />
&#160;&#160;<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3bac4a1be25f02eef9d4c28755d40e73fcc">Ok</a> = 200, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3ba4c9c5b2f0c45843fb21139636ac65334">PointlessCommand</a> = 202, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3baa179c6310d607c920b23a2d6ce2d61a7">SystemStatus</a> = 211, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3ba01821e4dc199adbf69ef65df4f949da7">DirectoryStatus</a> = 212, 
<br />
&#160;&#160;<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3ba5b006cb170dda08ade062b4fe1929927">FileStatus</a> = 213, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3ba90cc40f06a165f2eef3036f5a63ccad4">HelpMessage</a> = 214, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3baf9f5fd830fbc98405658fcdd1ed4b958">SystemType</a> = 215, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3ba94cd5a9201b7ebf0c10739860614e38a">ServiceReady</a> = 220, 
<br />
&#160;&#160;<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3bae070a7c775b991e22bbc94164c06a3e1">ClosingConnection</a> = 221, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3baca24974cc31d5076fb34effeb7c37459">DataConnectionOpened</a> = 225, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3ba326e2020413f73ab20d96e1425dc6c61">ClosingDataConnection</a> = 226, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3ba772b171084e6352b039a3190edd49d47">EnteringPassiveMode</a> = 227, 
<br />
&#160;&#160;<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3baed6a77a3599d7d2c99261e8fd67ddc02">LoggedIn</a> = 230, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3ba533ecde0d9d9fb8ced97451dafe478f4">FileActionOk</a> = 250, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3ba469897826bb8b8139df17bc60e584df1">DirectoryOk</a> = 257, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3baeb7f26cf02a13fc05d9e1d8a323b1dde">NeedPassword</a> = 331, 
<br />
&#160;&#160;<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3baa8c41b24d7fba52b82600c74929a7d8c">NeedAccountToLogIn</a> = 332, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3ba3e7c902cae306df22540129d1b9c3731">NeedInformation</a> = 350, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3ba831d98246d1bf42ce95e7f75bb34d485">ServiceUnavailable</a> = 421, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3ba0b82e3e39aa5ce3e9b3115abd04c74cf">DataConnectionUnavailable</a> = 425, 
<br />
&#160;&#160;<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3ba05e7e2eb62bf7d8709f5f6d37dbde7cb">TransferAborted</a> = 426, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3ba2d2f79c754ef2257e4e3ad96985506b4">FileActionAborted</a> = 450, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3ba5400391612ec91f15e64255a4c55b3c3">LocalError</a> = 451, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3bac5e00c7cb975030504b2afb86e47fa68">InsufficientStorageSpace</a> = 452, 
<br />
&#160;&#160;<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3ba4ccd31337b9478c6cf5089523e16b540">CommandUnknown</a> = 500, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3ba00a8672a96112ad00dc2f1117e1146ac">ParametersUnknown</a> = 501, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3bac91eba896240e927206c386f5bf8e32e">CommandNotImplemented</a> = 502, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3ba0547dfb381e953f77b7c5a2733c40613">BadCommandSequence</a> = 503, 
<br />
&#160;&#160;<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3ba91b4fde3e5e13d59a08c06310b29028d">ParameterNotImplemented</a> = 504, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3ba4d55199035de3c613fff260681ca762e">NotLoggedIn</a> = 530, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3baa19655e1a74e69425758933af91d0c65">NeedAccountToStore</a> = 532, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3bab1baeceb935584402decd35925a4e443">FileUnavailable</a> = 550, 
<br />
&#160;&#160;<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3ba54368544faf2ec0bfde88dded6920dfc">PageTypeUnknown</a> = 551, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3bab65332f3729d28c9f2551dfa2827dc0c">NotEnoughMemory</a> = 552, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3ba84de438a2c6c6bf461c1bc2f79eba577">FilenameNotAllowed</a> = 553, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3ba2832369b24738d47a832361b09fef964">InvalidResponse</a> = 1000, 
<br />
&#160;&#160;<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3ba099e88e94cf51258fd901177a37f7bb7">ConnectionFailed</a> = 1001, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3baf84c1847c12fe7216eca9a49af1b0cd7">ConnectionClosed</a> = 1002, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3ba94f4054b5814eb4fe0fc6d576376503a">InvalidFile</a> = 1003, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3ba9c0f2a9ad7404aa610eb835ba06724a4">RestartMarkerReply</a> = 110, 
<br />
&#160;&#160;<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3ba68f0497585e490250bc2985edb4201d3">ServiceReadySoon</a> = 120, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3bac40df58b564d1256c9dc7cbdaede9ad2">DataConnectionAlreadyOpened</a> = 125, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3bab31a5cb621b4097247dfd59565ae8b98">OpeningDataConnection</a> = 150, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3bac4a1be25f02eef9d4c28755d40e73fcc">Ok</a> = 200, 
<br />
&#160;&#160;<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3ba4c9c5b2f0c45843fb21139636ac65334">PointlessCommand</a> = 202, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3baa179c6310d607c920b23a2d6ce2d61a7">SystemStatus</a> = 211, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3ba01821e4dc199adbf69ef65df4f949da7">DirectoryStatus</a> = 212, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3ba5b006cb170dda08ade062b4fe1929927">FileStatus</a> = 213, 
<br />
&#160;&#160;<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3ba90cc40f06a165f2eef3036f5a63ccad4">HelpMessage</a> = 214, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3baf9f5fd830fbc98405658fcdd1ed4b958">SystemType</a> = 215, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3ba94cd5a9201b7ebf0c10739860614e38a">ServiceReady</a> = 220, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3bae070a7c775b991e22bbc94164c06a3e1">ClosingConnection</a> = 221, 
<br />
&#160;&#160;<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3baca24974cc31d5076fb34effeb7c37459">DataConnectionOpened</a> = 225, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3ba326e2020413f73ab20d96e1425dc6c61">ClosingDataConnection</a> = 226, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3ba772b171084e6352b039a3190edd49d47">EnteringPassiveMode</a> = 227, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3baed6a77a3599d7d2c99261e8fd67ddc02">LoggedIn</a> = 230, 
<br />
&#160;&#160;<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3ba533ecde0d9d9fb8ced97451dafe478f4">FileActionOk</a> = 250, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3ba469897826bb8b8139df17bc60e584df1">DirectoryOk</a> = 257, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3baeb7f26cf02a13fc05d9e1d8a323b1dde">NeedPassword</a> = 331, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3baa8c41b24d7fba52b82600c74929a7d8c">NeedAccountToLogIn</a> = 332, 
<br />
&#160;&#160;<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3ba3e7c902cae306df22540129d1b9c3731">NeedInformation</a> = 350, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3ba831d98246d1bf42ce95e7f75bb34d485">ServiceUnavailable</a> = 421, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3ba0b82e3e39aa5ce3e9b3115abd04c74cf">DataConnectionUnavailable</a> = 425, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3ba05e7e2eb62bf7d8709f5f6d37dbde7cb">TransferAborted</a> = 426, 
<br />
&#160;&#160;<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3ba2d2f79c754ef2257e4e3ad96985506b4">FileActionAborted</a> = 450, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3ba5400391612ec91f15e64255a4c55b3c3">LocalError</a> = 451, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3bac5e00c7cb975030504b2afb86e47fa68">InsufficientStorageSpace</a> = 452, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3ba4ccd31337b9478c6cf5089523e16b540">CommandUnknown</a> = 500, 
<br />
&#160;&#160;<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3ba00a8672a96112ad00dc2f1117e1146ac">ParametersUnknown</a> = 501, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3bac91eba896240e927206c386f5bf8e32e">CommandNotImplemented</a> = 502, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3ba0547dfb381e953f77b7c5a2733c40613">BadCommandSequence</a> = 503, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3ba91b4fde3e5e13d59a08c06310b29028d">ParameterNotImplemented</a> = 504, 
<br />
&#160;&#160;<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3ba4d55199035de3c613fff260681ca762e">NotLoggedIn</a> = 530, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3baa19655e1a74e69425758933af91d0c65">NeedAccountToStore</a> = 532, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3bab1baeceb935584402decd35925a4e443">FileUnavailable</a> = 550, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3ba54368544faf2ec0bfde88dded6920dfc">PageTypeUnknown</a> = 551, 
<br />
&#160;&#160;<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3bab65332f3729d28c9f2551dfa2827dc0c">NotEnoughMemory</a> = 552, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3ba84de438a2c6c6bf461c1bc2f79eba577">FilenameNotAllowed</a> = 553, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3ba2832369b24738d47a832361b09fef964">InvalidResponse</a> = 1000, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3ba099e88e94cf51258fd901177a37f7bb7">ConnectionFailed</a> = 1001, 
<br />
&#160;&#160;<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3baf84c1847c12fe7216eca9a49af1b0cd7">ConnectionClosed</a> = 1002, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3ba94f4054b5814eb4fe0fc6d576376503a">InvalidFile</a> = 1003
<br />
 }<tr class="memdesc:af81738f06b6f571761696291276acb3b"><td class="mdescLeft">&#160;</td><td class="mdescRight">Status codes possibly returned by a FTP response.  <a href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3b">More...</a><br /></td></tr>
<tr class="separator:af81738f06b6f571761696291276acb3b"><td class="memSeparator" colspan="2">&#160;</td></tr>
</td></tr>
<tr class="memitem:af81738f06b6f571761696291276acb3b"><td class="memItemLeft" align="right" valign="top">enum &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3b">Status</a> { <br />
&#160;&#160;<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3ba9c0f2a9ad7404aa610eb835ba06724a4">RestartMarkerReply</a> = 110, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3ba68f0497585e490250bc2985edb4201d3">ServiceReadySoon</a> = 120, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3bac40df58b564d1256c9dc7cbdaede9ad2">DataConnectionAlreadyOpened</a> = 125, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3bab31a5cb621b4097247dfd59565ae8b98">OpeningDataConnection</a> = 150, 
<br />
&#160;&#160;<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3bac4a1be25f02eef9d4c28755d40e73fcc">Ok</a> = 200, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3ba4c9c5b2f0c45843fb21139636ac65334">PointlessCommand</a> = 202, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3baa179c6310d607c920b23a2d6ce2d61a7">SystemStatus</a> = 211, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3ba01821e4dc199adbf69ef65df4f949da7">DirectoryStatus</a> = 212, 
<br />
&#160;&#160;<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3ba5b006cb170dda08ade062b4fe1929927">FileStatus</a> = 213, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3ba90cc40f06a165f2eef3036f5a63ccad4">HelpMessage</a> = 214, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3baf9f5fd830fbc98405658fcdd1ed4b958">SystemType</a> = 215, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3ba94cd5a9201b7ebf0c10739860614e38a">ServiceReady</a> = 220, 
<br />
&#160;&#160;<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3bae070a7c775b991e22bbc94164c06a3e1">ClosingConnection</a> = 221, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3baca24974cc31d5076fb34effeb7c37459">DataConnectionOpened</a> = 225, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3ba326e2020413f73ab20d96e1425dc6c61">ClosingDataConnection</a> = 226, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3ba772b171084e6352b039a3190edd49d47">EnteringPassiveMode</a> = 227, 
<br />
&#160;&#160;<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3baed6a77a3599d7d2c99261e8fd67ddc02">LoggedIn</a> = 230, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3ba533ecde0d9d9fb8ced97451dafe478f4">FileActionOk</a> = 250, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3ba469897826bb8b8139df17bc60e584df1">DirectoryOk</a> = 257, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3baeb7f26cf02a13fc05d9e1d8a323b1dde">NeedPassword</a> = 331, 
<br />
&#160;&#160;<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3baa8c41b24d7fba52b82600c74929a7d8c">NeedAccountToLogIn</a> = 332, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3ba3e7c902cae306df22540129d1b9c3731">NeedInformation</a> = 350, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3ba831d98246d1bf42ce95e7f75bb34d485">ServiceUnavailable</a> = 421, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3ba0b82e3e39aa5ce3e9b3115abd04c74cf">DataConnectionUnavailable</a> = 425, 
<br />
&#160;&#160;<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3ba05e7e2eb62bf7d8709f5f6d37dbde7cb">TransferAborted</a> = 426, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3ba2d2f79c754ef2257e4e3ad96985506b4">FileActionAborted</a> = 450, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3ba5400391612ec91f15e64255a4c55b3c3">LocalError</a> = 451, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3bac5e00c7cb975030504b2afb86e47fa68">InsufficientStorageSpace</a> = 452, 
<br />
&#160;&#160;<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3ba4ccd31337b9478c6cf5089523e16b540">CommandUnknown</a> = 500, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3ba00a8672a96112ad00dc2f1117e1146ac">ParametersUnknown</a> = 501, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3bac91eba896240e927206c386f5bf8e32e">CommandNotImplemented</a> = 502, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3ba0547dfb381e953f77b7c5a2733c40613">BadCommandSequence</a> = 503, 
<br />
&#160;&#160;<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3ba91b4fde3e5e13d59a08c06310b29028d">ParameterNotImplemented</a> = 504, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3ba4d55199035de3c613fff260681ca762e">NotLoggedIn</a> = 530, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3baa19655e1a74e69425758933af91d0c65">NeedAccountToStore</a> = 532, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3bab1baeceb935584402decd35925a4e443">FileUnavailable</a> = 550, 
<br />
&#160;&#160;<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3ba54368544faf2ec0bfde88dded6920dfc">PageTypeUnknown</a> = 551, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3bab65332f3729d28c9f2551dfa2827dc0c">NotEnoughMemory</a> = 552, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3ba84de438a2c6c6bf461c1bc2f79eba577">FilenameNotAllowed</a> = 553, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3ba2832369b24738d47a832361b09fef964">InvalidResponse</a> = 1000, 
<br />
&#160;&#160;<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3ba099e88e94cf51258fd901177a37f7bb7">ConnectionFailed</a> = 1001, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3baf84c1847c12fe7216eca9a49af1b0cd7">ConnectionClosed</a> = 1002, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3ba94f4054b5814eb4fe0fc6d576376503a">InvalidFile</a> = 1003, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3ba9c0f2a9ad7404aa610eb835ba06724a4">RestartMarkerReply</a> = 110, 
<br />
&#160;&#160;<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3ba68f0497585e490250bc2985edb4201d3">ServiceReadySoon</a> = 120, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3bac40df58b564d1256c9dc7cbdaede9ad2">DataConnectionAlreadyOpened</a> = 125, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3bab31a5cb621b4097247dfd59565ae8b98">OpeningDataConnection</a> = 150, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3bac4a1be25f02eef9d4c28755d40e73fcc">Ok</a> = 200, 
<br />
&#160;&#160;<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3ba4c9c5b2f0c45843fb21139636ac65334">PointlessCommand</a> = 202, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3baa179c6310d607c920b23a2d6ce2d61a7">SystemStatus</a> = 211, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3ba01821e4dc199adbf69ef65df4f949da7">DirectoryStatus</a> = 212, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3ba5b006cb170dda08ade062b4fe1929927">FileStatus</a> = 213, 
<br />
&#160;&#160;<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3ba90cc40f06a165f2eef3036f5a63ccad4">HelpMessage</a> = 214, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3baf9f5fd830fbc98405658fcdd1ed4b958">SystemType</a> = 215, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3ba94cd5a9201b7ebf0c10739860614e38a">ServiceReady</a> = 220, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3bae070a7c775b991e22bbc94164c06a3e1">ClosingConnection</a> = 221, 
<br />
&#160;&#160;<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3baca24974cc31d5076fb34effeb7c37459">DataConnectionOpened</a> = 225, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3ba326e2020413f73ab20d96e1425dc6c61">ClosingDataConnection</a> = 226, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3ba772b171084e6352b039a3190edd49d47">EnteringPassiveMode</a> = 227, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3baed6a77a3599d7d2c99261e8fd67ddc02">LoggedIn</a> = 230, 
<br />
&#160;&#160;<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3ba533ecde0d9d9fb8ced97451dafe478f4">FileActionOk</a> = 250, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3ba469897826bb8b8139df17bc60e584df1">DirectoryOk</a> = 257, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3baeb7f26cf02a13fc05d9e1d8a323b1dde">NeedPassword</a> = 331, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3baa8c41b24d7fba52b82600c74929a7d8c">NeedAccountToLogIn</a> = 332, 
<br />
&#160;&#160;<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3ba3e7c902cae306df22540129d1b9c3731">NeedInformation</a> = 350, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3ba831d98246d1bf42ce95e7f75bb34d485">ServiceUnavailable</a> = 421, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3ba0b82e3e39aa5ce3e9b3115abd04c74cf">DataConnectionUnavailable</a> = 425, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3ba05e7e2eb62bf7d8709f5f6d37dbde7cb">TransferAborted</a> = 426, 
<br />
&#160;&#160;<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3ba2d2f79c754ef2257e4e3ad96985506b4">FileActionAborted</a> = 450, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3ba5400391612ec91f15e64255a4c55b3c3">LocalError</a> = 451, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3bac5e00c7cb975030504b2afb86e47fa68">InsufficientStorageSpace</a> = 452, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3ba4ccd31337b9478c6cf5089523e16b540">CommandUnknown</a> = 500, 
<br />
&#160;&#160;<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3ba00a8672a96112ad00dc2f1117e1146ac">ParametersUnknown</a> = 501, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3bac91eba896240e927206c386f5bf8e32e">CommandNotImplemented</a> = 502, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3ba0547dfb381e953f77b7c5a2733c40613">BadCommandSequence</a> = 503, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3ba91b4fde3e5e13d59a08c06310b29028d">ParameterNotImplemented</a> = 504, 
<br />
&#160;&#160;<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3ba4d55199035de3c613fff260681ca762e">NotLoggedIn</a> = 530, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3baa19655e1a74e69425758933af91d0c65">NeedAccountToStore</a> = 532, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3bab1baeceb935584402decd35925a4e443">FileUnavailable</a> = 550, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3ba54368544faf2ec0bfde88dded6920dfc">PageTypeUnknown</a> = 551, 
<br />
&#160;&#160;<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3bab65332f3729d28c9f2551dfa2827dc0c">NotEnoughMemory</a> = 552, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3ba84de438a2c6c6bf461c1bc2f79eba577">FilenameNotAllowed</a> = 553, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3ba2832369b24738d47a832361b09fef964">InvalidResponse</a> = 1000, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3ba099e88e94cf51258fd901177a37f7bb7">ConnectionFailed</a> = 1001, 
<br />
&#160;&#160;<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3baf84c1847c12fe7216eca9a49af1b0cd7">ConnectionClosed</a> = 1002, 
<a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3ba94f4054b5814eb4fe0fc6d576376503a">InvalidFile</a> = 1003
<br />
 }<tr class="memdesc:af81738f06b6f571761696291276acb3b"><td class="mdescLeft">&#160;</td><td class="mdescRight">Status codes possibly returned by a FTP response.  <a href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3b">More...</a><br /></td></tr>
<tr class="separator:af81738f06b6f571761696291276acb3b"><td class="memSeparator" colspan="2">&#160;</td></tr>
</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr class="memitem:a7e98d0aed70105c71adb52e5b6ce0bb8"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classsf_1_1Ftp_1_1ListingResponse.php#a7e98d0aed70105c71adb52e5b6ce0bb8">ListingResponse</a> (const <a class="el" href="classsf_1_1Ftp_1_1Response.php">Response</a> &amp;response, const std::string &amp;data)</td></tr>
<tr class="memdesc:a7e98d0aed70105c71adb52e5b6ce0bb8"><td class="mdescLeft">&#160;</td><td class="mdescRight">Default constructor.  <a href="#a7e98d0aed70105c71adb52e5b6ce0bb8">More...</a><br /></td></tr>
<tr class="separator:a7e98d0aed70105c71adb52e5b6ce0bb8"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a5f0771b52a966bf25b33a70602b6f97f"><td class="memItemLeft" align="right" valign="top">const std::vector&lt; std::string &gt; &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classsf_1_1Ftp_1_1ListingResponse.php#a5f0771b52a966bf25b33a70602b6f97f">getListing</a> () const </td></tr>
<tr class="memdesc:a5f0771b52a966bf25b33a70602b6f97f"><td class="mdescLeft">&#160;</td><td class="mdescRight">Return the array of directory/file names.  <a href="#a5f0771b52a966bf25b33a70602b6f97f">More...</a><br /></td></tr>
<tr class="separator:a5f0771b52a966bf25b33a70602b6f97f"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a7e98d0aed70105c71adb52e5b6ce0bb8"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classsf_1_1Ftp_1_1ListingResponse.php#a7e98d0aed70105c71adb52e5b6ce0bb8">ListingResponse</a> (const <a class="el" href="classsf_1_1Ftp_1_1Response.php">Response</a> &amp;response, const std::string &amp;data)</td></tr>
<tr class="memdesc:a7e98d0aed70105c71adb52e5b6ce0bb8"><td class="mdescLeft">&#160;</td><td class="mdescRight">Default constructor.  <a href="#a7e98d0aed70105c71adb52e5b6ce0bb8">More...</a><br /></td></tr>
<tr class="separator:a7e98d0aed70105c71adb52e5b6ce0bb8"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a5f0771b52a966bf25b33a70602b6f97f"><td class="memItemLeft" align="right" valign="top">const std::vector&lt; std::string &gt; &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classsf_1_1Ftp_1_1ListingResponse.php#a5f0771b52a966bf25b33a70602b6f97f">getListing</a> () const </td></tr>
<tr class="memdesc:a5f0771b52a966bf25b33a70602b6f97f"><td class="mdescLeft">&#160;</td><td class="mdescRight">Return the array of directory/file names.  <a href="#a5f0771b52a966bf25b33a70602b6f97f">More...</a><br /></td></tr>
<tr class="separator:a5f0771b52a966bf25b33a70602b6f97f"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a4dadbe0fe0a3ef2d571a017e1645e675"><td class="memItemLeft" align="right" valign="top">bool&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classsf_1_1Ftp_1_1Response.php#a4dadbe0fe0a3ef2d571a017e1645e675">isOk</a> () const </td></tr>
<tr class="memdesc:a4dadbe0fe0a3ef2d571a017e1645e675"><td class="mdescLeft">&#160;</td><td class="mdescRight">Check if the status code means a success.  <a href="#a4dadbe0fe0a3ef2d571a017e1645e675">More...</a><br /></td></tr>
<tr class="separator:a4dadbe0fe0a3ef2d571a017e1645e675"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a4dadbe0fe0a3ef2d571a017e1645e675"><td class="memItemLeft" align="right" valign="top">bool&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classsf_1_1Ftp_1_1Response.php#a4dadbe0fe0a3ef2d571a017e1645e675">isOk</a> () const </td></tr>
<tr class="memdesc:a4dadbe0fe0a3ef2d571a017e1645e675"><td class="mdescLeft">&#160;</td><td class="mdescRight">Check if the status code means a success.  <a href="#a4dadbe0fe0a3ef2d571a017e1645e675">More...</a><br /></td></tr>
<tr class="separator:a4dadbe0fe0a3ef2d571a017e1645e675"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ac7f937b3883d1c4fbc75c003a1786aaa"><td class="memItemLeft" align="right" valign="top"><a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3b">Status</a>&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classsf_1_1Ftp_1_1Response.php#ac7f937b3883d1c4fbc75c003a1786aaa">getStatus</a> () const </td></tr>
<tr class="memdesc:ac7f937b3883d1c4fbc75c003a1786aaa"><td class="mdescLeft">&#160;</td><td class="mdescRight">Get the status code of the response.  <a href="#ac7f937b3883d1c4fbc75c003a1786aaa">More...</a><br /></td></tr>
<tr class="separator:ac7f937b3883d1c4fbc75c003a1786aaa"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ac7f937b3883d1c4fbc75c003a1786aaa"><td class="memItemLeft" align="right" valign="top"><a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3b">Status</a>&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classsf_1_1Ftp_1_1Response.php#ac7f937b3883d1c4fbc75c003a1786aaa">getStatus</a> () const </td></tr>
<tr class="memdesc:ac7f937b3883d1c4fbc75c003a1786aaa"><td class="mdescLeft">&#160;</td><td class="mdescRight">Get the status code of the response.  <a href="#ac7f937b3883d1c4fbc75c003a1786aaa">More...</a><br /></td></tr>
<tr class="separator:ac7f937b3883d1c4fbc75c003a1786aaa"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a0015675c528a4a84a671484b9e5499d6"><td class="memItemLeft" align="right" valign="top">const std::string &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classsf_1_1Ftp_1_1Response.php#a0015675c528a4a84a671484b9e5499d6">getMessage</a> () const </td></tr>
<tr class="memdesc:a0015675c528a4a84a671484b9e5499d6"><td class="mdescLeft">&#160;</td><td class="mdescRight">Get the full message contained in the response.  <a href="#a0015675c528a4a84a671484b9e5499d6">More...</a><br /></td></tr>
<tr class="separator:a0015675c528a4a84a671484b9e5499d6"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a0015675c528a4a84a671484b9e5499d6"><td class="memItemLeft" align="right" valign="top">const std::string &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classsf_1_1Ftp_1_1Response.php#a0015675c528a4a84a671484b9e5499d6">getMessage</a> () const </td></tr>
<tr class="memdesc:a0015675c528a4a84a671484b9e5499d6"><td class="mdescLeft">&#160;</td><td class="mdescRight">Get the full message contained in the response.  <a href="#a0015675c528a4a84a671484b9e5499d6">More...</a><br /></td></tr>
<tr class="separator:a0015675c528a4a84a671484b9e5499d6"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><p>Specialization of FTP response returning a filename listing. </p>

<p>Definition at line <a class="el" href="include_2SFML_2Network_2Ftp_8hpp_source.php#l00221">221</a> of file <a class="el" href="include_2SFML_2Network_2Ftp_8hpp_source.php">include/SFML/Network/Ftp.hpp</a>.</p>
</div><h2 class="groupheader">Member Enumeration Documentation</h2>
<a class="anchor" id="af81738f06b6f571761696291276acb3b"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">enum <a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3b">sf::Ftp::Response::Status</a></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inherited</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>Status codes possibly returned by a FTP response. </p>
<table class="fieldtable">
<tr><th colspan="2">Enumerator</th></tr><tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3ba9c0f2a9ad7404aa610eb835ba06724a4"></a>RestartMarkerReply&#160;</td><td class="fielddoc">
<p>Restart marker reply. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3ba68f0497585e490250bc2985edb4201d3"></a>ServiceReadySoon&#160;</td><td class="fielddoc">
<p>Service ready in N minutes. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3bac40df58b564d1256c9dc7cbdaede9ad2"></a>DataConnectionAlreadyOpened&#160;</td><td class="fielddoc">
<p>Data connection already opened, transfer starting. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3bab31a5cb621b4097247dfd59565ae8b98"></a>OpeningDataConnection&#160;</td><td class="fielddoc">
<p>File status ok, about to open data connection. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3bac4a1be25f02eef9d4c28755d40e73fcc"></a>Ok&#160;</td><td class="fielddoc">
<p>Command ok. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3ba4c9c5b2f0c45843fb21139636ac65334"></a>PointlessCommand&#160;</td><td class="fielddoc">
<p>Command not implemented. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3baa179c6310d607c920b23a2d6ce2d61a7"></a>SystemStatus&#160;</td><td class="fielddoc">
<p>System status, or system help reply. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3ba01821e4dc199adbf69ef65df4f949da7"></a>DirectoryStatus&#160;</td><td class="fielddoc">
<p>Directory status. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3ba5b006cb170dda08ade062b4fe1929927"></a>FileStatus&#160;</td><td class="fielddoc">
<p>File status. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3ba90cc40f06a165f2eef3036f5a63ccad4"></a>HelpMessage&#160;</td><td class="fielddoc">
<p>Help message. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3baf9f5fd830fbc98405658fcdd1ed4b958"></a>SystemType&#160;</td><td class="fielddoc">
<p>NAME system type, where NAME is an official system name from the list in the Assigned Numbers document. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3ba94cd5a9201b7ebf0c10739860614e38a"></a>ServiceReady&#160;</td><td class="fielddoc">
<p>Service ready for new user. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3bae070a7c775b991e22bbc94164c06a3e1"></a>ClosingConnection&#160;</td><td class="fielddoc">
<p>Service closing control connection. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3baca24974cc31d5076fb34effeb7c37459"></a>DataConnectionOpened&#160;</td><td class="fielddoc">
<p>Data connection open, no transfer in progress. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3ba326e2020413f73ab20d96e1425dc6c61"></a>ClosingDataConnection&#160;</td><td class="fielddoc">
<p>Closing data connection, requested file action successful. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3ba772b171084e6352b039a3190edd49d47"></a>EnteringPassiveMode&#160;</td><td class="fielddoc">
<p>Entering passive mode. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3baed6a77a3599d7d2c99261e8fd67ddc02"></a>LoggedIn&#160;</td><td class="fielddoc">
<p>User logged in, proceed. Logged out if appropriate. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3ba533ecde0d9d9fb8ced97451dafe478f4"></a>FileActionOk&#160;</td><td class="fielddoc">
<p>Requested file action ok. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3ba469897826bb8b8139df17bc60e584df1"></a>DirectoryOk&#160;</td><td class="fielddoc">
<p>PATHNAME created. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3baeb7f26cf02a13fc05d9e1d8a323b1dde"></a>NeedPassword&#160;</td><td class="fielddoc">
<p>User name ok, need password. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3baa8c41b24d7fba52b82600c74929a7d8c"></a>NeedAccountToLogIn&#160;</td><td class="fielddoc">
<p>Need account for login. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3ba3e7c902cae306df22540129d1b9c3731"></a>NeedInformation&#160;</td><td class="fielddoc">
<p>Requested file action pending further information. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3ba831d98246d1bf42ce95e7f75bb34d485"></a>ServiceUnavailable&#160;</td><td class="fielddoc">
<p>Service not available, closing control connection. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3ba0b82e3e39aa5ce3e9b3115abd04c74cf"></a>DataConnectionUnavailable&#160;</td><td class="fielddoc">
<p>Can't open data connection. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3ba05e7e2eb62bf7d8709f5f6d37dbde7cb"></a>TransferAborted&#160;</td><td class="fielddoc">
<p>Connection closed, transfer aborted. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3ba2d2f79c754ef2257e4e3ad96985506b4"></a>FileActionAborted&#160;</td><td class="fielddoc">
<p>Requested file action not taken. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3ba5400391612ec91f15e64255a4c55b3c3"></a>LocalError&#160;</td><td class="fielddoc">
<p>Requested action aborted, local error in processing. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3bac5e00c7cb975030504b2afb86e47fa68"></a>InsufficientStorageSpace&#160;</td><td class="fielddoc">
<p>Requested action not taken; insufficient storage space in system, file unavailable. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3ba4ccd31337b9478c6cf5089523e16b540"></a>CommandUnknown&#160;</td><td class="fielddoc">
<p>Syntax error, command unrecognized. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3ba00a8672a96112ad00dc2f1117e1146ac"></a>ParametersUnknown&#160;</td><td class="fielddoc">
<p>Syntax error in parameters or arguments. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3bac91eba896240e927206c386f5bf8e32e"></a>CommandNotImplemented&#160;</td><td class="fielddoc">
<p>Command not implemented. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3ba0547dfb381e953f77b7c5a2733c40613"></a>BadCommandSequence&#160;</td><td class="fielddoc">
<p>Bad sequence of commands. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3ba91b4fde3e5e13d59a08c06310b29028d"></a>ParameterNotImplemented&#160;</td><td class="fielddoc">
<p>Command not implemented for that parameter. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3ba4d55199035de3c613fff260681ca762e"></a>NotLoggedIn&#160;</td><td class="fielddoc">
<p>Not logged in. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3baa19655e1a74e69425758933af91d0c65"></a>NeedAccountToStore&#160;</td><td class="fielddoc">
<p>Need account for storing files. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3bab1baeceb935584402decd35925a4e443"></a>FileUnavailable&#160;</td><td class="fielddoc">
<p>Requested action not taken, file unavailable. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3ba54368544faf2ec0bfde88dded6920dfc"></a>PageTypeUnknown&#160;</td><td class="fielddoc">
<p>Requested action aborted, page type unknown. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3bab65332f3729d28c9f2551dfa2827dc0c"></a>NotEnoughMemory&#160;</td><td class="fielddoc">
<p>Requested file action aborted, exceeded storage allocation. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3ba84de438a2c6c6bf461c1bc2f79eba577"></a>FilenameNotAllowed&#160;</td><td class="fielddoc">
<p>Requested action not taken, file name not allowed. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3ba2832369b24738d47a832361b09fef964"></a>InvalidResponse&#160;</td><td class="fielddoc">
<p>Not part of the FTP standard, generated by SFML when a received response cannot be parsed. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3ba099e88e94cf51258fd901177a37f7bb7"></a>ConnectionFailed&#160;</td><td class="fielddoc">
<p>Not part of the FTP standard, generated by SFML when the low-level socket connection with the server fails. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3baf84c1847c12fe7216eca9a49af1b0cd7"></a>ConnectionClosed&#160;</td><td class="fielddoc">
<p>Not part of the FTP standard, generated by SFML when the low-level socket connection is unexpectedly closed. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3ba94f4054b5814eb4fe0fc6d576376503a"></a>InvalidFile&#160;</td><td class="fielddoc">
<p>Not part of the FTP standard, generated by SFML when a local file cannot be read or written. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3ba9c0f2a9ad7404aa610eb835ba06724a4"></a>RestartMarkerReply&#160;</td><td class="fielddoc">
<p>Restart marker reply. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3ba68f0497585e490250bc2985edb4201d3"></a>ServiceReadySoon&#160;</td><td class="fielddoc">
<p>Service ready in N minutes. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3bac40df58b564d1256c9dc7cbdaede9ad2"></a>DataConnectionAlreadyOpened&#160;</td><td class="fielddoc">
<p>Data connection already opened, transfer starting. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3bab31a5cb621b4097247dfd59565ae8b98"></a>OpeningDataConnection&#160;</td><td class="fielddoc">
<p>File status ok, about to open data connection. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3bac4a1be25f02eef9d4c28755d40e73fcc"></a>Ok&#160;</td><td class="fielddoc">
<p>Command ok. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3ba4c9c5b2f0c45843fb21139636ac65334"></a>PointlessCommand&#160;</td><td class="fielddoc">
<p>Command not implemented. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3baa179c6310d607c920b23a2d6ce2d61a7"></a>SystemStatus&#160;</td><td class="fielddoc">
<p>System status, or system help reply. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3ba01821e4dc199adbf69ef65df4f949da7"></a>DirectoryStatus&#160;</td><td class="fielddoc">
<p>Directory status. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3ba5b006cb170dda08ade062b4fe1929927"></a>FileStatus&#160;</td><td class="fielddoc">
<p>File status. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3ba90cc40f06a165f2eef3036f5a63ccad4"></a>HelpMessage&#160;</td><td class="fielddoc">
<p>Help message. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3baf9f5fd830fbc98405658fcdd1ed4b958"></a>SystemType&#160;</td><td class="fielddoc">
<p>NAME system type, where NAME is an official system name from the list in the Assigned Numbers document. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3ba94cd5a9201b7ebf0c10739860614e38a"></a>ServiceReady&#160;</td><td class="fielddoc">
<p>Service ready for new user. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3bae070a7c775b991e22bbc94164c06a3e1"></a>ClosingConnection&#160;</td><td class="fielddoc">
<p>Service closing control connection. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3baca24974cc31d5076fb34effeb7c37459"></a>DataConnectionOpened&#160;</td><td class="fielddoc">
<p>Data connection open, no transfer in progress. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3ba326e2020413f73ab20d96e1425dc6c61"></a>ClosingDataConnection&#160;</td><td class="fielddoc">
<p>Closing data connection, requested file action successful. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3ba772b171084e6352b039a3190edd49d47"></a>EnteringPassiveMode&#160;</td><td class="fielddoc">
<p>Entering passive mode. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3baed6a77a3599d7d2c99261e8fd67ddc02"></a>LoggedIn&#160;</td><td class="fielddoc">
<p>User logged in, proceed. Logged out if appropriate. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3ba533ecde0d9d9fb8ced97451dafe478f4"></a>FileActionOk&#160;</td><td class="fielddoc">
<p>Requested file action ok. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3ba469897826bb8b8139df17bc60e584df1"></a>DirectoryOk&#160;</td><td class="fielddoc">
<p>PATHNAME created. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3baeb7f26cf02a13fc05d9e1d8a323b1dde"></a>NeedPassword&#160;</td><td class="fielddoc">
<p>User name ok, need password. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3baa8c41b24d7fba52b82600c74929a7d8c"></a>NeedAccountToLogIn&#160;</td><td class="fielddoc">
<p>Need account for login. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3ba3e7c902cae306df22540129d1b9c3731"></a>NeedInformation&#160;</td><td class="fielddoc">
<p>Requested file action pending further information. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3ba831d98246d1bf42ce95e7f75bb34d485"></a>ServiceUnavailable&#160;</td><td class="fielddoc">
<p>Service not available, closing control connection. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3ba0b82e3e39aa5ce3e9b3115abd04c74cf"></a>DataConnectionUnavailable&#160;</td><td class="fielddoc">
<p>Can't open data connection. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3ba05e7e2eb62bf7d8709f5f6d37dbde7cb"></a>TransferAborted&#160;</td><td class="fielddoc">
<p>Connection closed, transfer aborted. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3ba2d2f79c754ef2257e4e3ad96985506b4"></a>FileActionAborted&#160;</td><td class="fielddoc">
<p>Requested file action not taken. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3ba5400391612ec91f15e64255a4c55b3c3"></a>LocalError&#160;</td><td class="fielddoc">
<p>Requested action aborted, local error in processing. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3bac5e00c7cb975030504b2afb86e47fa68"></a>InsufficientStorageSpace&#160;</td><td class="fielddoc">
<p>Requested action not taken; insufficient storage space in system, file unavailable. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3ba4ccd31337b9478c6cf5089523e16b540"></a>CommandUnknown&#160;</td><td class="fielddoc">
<p>Syntax error, command unrecognized. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3ba00a8672a96112ad00dc2f1117e1146ac"></a>ParametersUnknown&#160;</td><td class="fielddoc">
<p>Syntax error in parameters or arguments. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3bac91eba896240e927206c386f5bf8e32e"></a>CommandNotImplemented&#160;</td><td class="fielddoc">
<p>Command not implemented. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3ba0547dfb381e953f77b7c5a2733c40613"></a>BadCommandSequence&#160;</td><td class="fielddoc">
<p>Bad sequence of commands. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3ba91b4fde3e5e13d59a08c06310b29028d"></a>ParameterNotImplemented&#160;</td><td class="fielddoc">
<p>Command not implemented for that parameter. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3ba4d55199035de3c613fff260681ca762e"></a>NotLoggedIn&#160;</td><td class="fielddoc">
<p>Not logged in. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3baa19655e1a74e69425758933af91d0c65"></a>NeedAccountToStore&#160;</td><td class="fielddoc">
<p>Need account for storing files. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3bab1baeceb935584402decd35925a4e443"></a>FileUnavailable&#160;</td><td class="fielddoc">
<p>Requested action not taken, file unavailable. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3ba54368544faf2ec0bfde88dded6920dfc"></a>PageTypeUnknown&#160;</td><td class="fielddoc">
<p>Requested action aborted, page type unknown. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3bab65332f3729d28c9f2551dfa2827dc0c"></a>NotEnoughMemory&#160;</td><td class="fielddoc">
<p>Requested file action aborted, exceeded storage allocation. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3ba84de438a2c6c6bf461c1bc2f79eba577"></a>FilenameNotAllowed&#160;</td><td class="fielddoc">
<p>Requested action not taken, file name not allowed. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3ba2832369b24738d47a832361b09fef964"></a>InvalidResponse&#160;</td><td class="fielddoc">
<p>Not part of the FTP standard, generated by SFML when a received response cannot be parsed. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3ba099e88e94cf51258fd901177a37f7bb7"></a>ConnectionFailed&#160;</td><td class="fielddoc">
<p>Not part of the FTP standard, generated by SFML when the low-level socket connection with the server fails. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3baf84c1847c12fe7216eca9a49af1b0cd7"></a>ConnectionClosed&#160;</td><td class="fielddoc">
<p>Not part of the FTP standard, generated by SFML when the low-level socket connection is unexpectedly closed. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3ba94f4054b5814eb4fe0fc6d576376503a"></a>InvalidFile&#160;</td><td class="fielddoc">
<p>Not part of the FTP standard, generated by SFML when a local file cannot be read or written. </p>
</td></tr>
</table>

<p>Definition at line <a class="el" href="include_2SFML_2Network_2Ftp_8hpp_source.php#l00074">74</a> of file <a class="el" href="include_2SFML_2Network_2Ftp_8hpp_source.php">include/SFML/Network/Ftp.hpp</a>.</p>

</div>
</div>
<a class="anchor" id="af81738f06b6f571761696291276acb3b"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">enum <a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3b">sf::Ftp::Response::Status</a></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inherited</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>Status codes possibly returned by a FTP response. </p>
<table class="fieldtable">
<tr><th colspan="2">Enumerator</th></tr><tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3ba9c0f2a9ad7404aa610eb835ba06724a4"></a>RestartMarkerReply&#160;</td><td class="fielddoc">
<p>Restart marker reply. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3ba68f0497585e490250bc2985edb4201d3"></a>ServiceReadySoon&#160;</td><td class="fielddoc">
<p>Service ready in N minutes. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3bac40df58b564d1256c9dc7cbdaede9ad2"></a>DataConnectionAlreadyOpened&#160;</td><td class="fielddoc">
<p>Data connection already opened, transfer starting. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3bab31a5cb621b4097247dfd59565ae8b98"></a>OpeningDataConnection&#160;</td><td class="fielddoc">
<p>File status ok, about to open data connection. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3bac4a1be25f02eef9d4c28755d40e73fcc"></a>Ok&#160;</td><td class="fielddoc">
<p>Command ok. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3ba4c9c5b2f0c45843fb21139636ac65334"></a>PointlessCommand&#160;</td><td class="fielddoc">
<p>Command not implemented. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3baa179c6310d607c920b23a2d6ce2d61a7"></a>SystemStatus&#160;</td><td class="fielddoc">
<p>System status, or system help reply. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3ba01821e4dc199adbf69ef65df4f949da7"></a>DirectoryStatus&#160;</td><td class="fielddoc">
<p>Directory status. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3ba5b006cb170dda08ade062b4fe1929927"></a>FileStatus&#160;</td><td class="fielddoc">
<p>File status. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3ba90cc40f06a165f2eef3036f5a63ccad4"></a>HelpMessage&#160;</td><td class="fielddoc">
<p>Help message. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3baf9f5fd830fbc98405658fcdd1ed4b958"></a>SystemType&#160;</td><td class="fielddoc">
<p>NAME system type, where NAME is an official system name from the list in the Assigned Numbers document. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3ba94cd5a9201b7ebf0c10739860614e38a"></a>ServiceReady&#160;</td><td class="fielddoc">
<p>Service ready for new user. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3bae070a7c775b991e22bbc94164c06a3e1"></a>ClosingConnection&#160;</td><td class="fielddoc">
<p>Service closing control connection. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3baca24974cc31d5076fb34effeb7c37459"></a>DataConnectionOpened&#160;</td><td class="fielddoc">
<p>Data connection open, no transfer in progress. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3ba326e2020413f73ab20d96e1425dc6c61"></a>ClosingDataConnection&#160;</td><td class="fielddoc">
<p>Closing data connection, requested file action successful. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3ba772b171084e6352b039a3190edd49d47"></a>EnteringPassiveMode&#160;</td><td class="fielddoc">
<p>Entering passive mode. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3baed6a77a3599d7d2c99261e8fd67ddc02"></a>LoggedIn&#160;</td><td class="fielddoc">
<p>User logged in, proceed. Logged out if appropriate. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3ba533ecde0d9d9fb8ced97451dafe478f4"></a>FileActionOk&#160;</td><td class="fielddoc">
<p>Requested file action ok. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3ba469897826bb8b8139df17bc60e584df1"></a>DirectoryOk&#160;</td><td class="fielddoc">
<p>PATHNAME created. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3baeb7f26cf02a13fc05d9e1d8a323b1dde"></a>NeedPassword&#160;</td><td class="fielddoc">
<p>User name ok, need password. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3baa8c41b24d7fba52b82600c74929a7d8c"></a>NeedAccountToLogIn&#160;</td><td class="fielddoc">
<p>Need account for login. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3ba3e7c902cae306df22540129d1b9c3731"></a>NeedInformation&#160;</td><td class="fielddoc">
<p>Requested file action pending further information. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3ba831d98246d1bf42ce95e7f75bb34d485"></a>ServiceUnavailable&#160;</td><td class="fielddoc">
<p>Service not available, closing control connection. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3ba0b82e3e39aa5ce3e9b3115abd04c74cf"></a>DataConnectionUnavailable&#160;</td><td class="fielddoc">
<p>Can't open data connection. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3ba05e7e2eb62bf7d8709f5f6d37dbde7cb"></a>TransferAborted&#160;</td><td class="fielddoc">
<p>Connection closed, transfer aborted. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3ba2d2f79c754ef2257e4e3ad96985506b4"></a>FileActionAborted&#160;</td><td class="fielddoc">
<p>Requested file action not taken. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3ba5400391612ec91f15e64255a4c55b3c3"></a>LocalError&#160;</td><td class="fielddoc">
<p>Requested action aborted, local error in processing. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3bac5e00c7cb975030504b2afb86e47fa68"></a>InsufficientStorageSpace&#160;</td><td class="fielddoc">
<p>Requested action not taken; insufficient storage space in system, file unavailable. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3ba4ccd31337b9478c6cf5089523e16b540"></a>CommandUnknown&#160;</td><td class="fielddoc">
<p>Syntax error, command unrecognized. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3ba00a8672a96112ad00dc2f1117e1146ac"></a>ParametersUnknown&#160;</td><td class="fielddoc">
<p>Syntax error in parameters or arguments. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3bac91eba896240e927206c386f5bf8e32e"></a>CommandNotImplemented&#160;</td><td class="fielddoc">
<p>Command not implemented. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3ba0547dfb381e953f77b7c5a2733c40613"></a>BadCommandSequence&#160;</td><td class="fielddoc">
<p>Bad sequence of commands. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3ba91b4fde3e5e13d59a08c06310b29028d"></a>ParameterNotImplemented&#160;</td><td class="fielddoc">
<p>Command not implemented for that parameter. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3ba4d55199035de3c613fff260681ca762e"></a>NotLoggedIn&#160;</td><td class="fielddoc">
<p>Not logged in. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3baa19655e1a74e69425758933af91d0c65"></a>NeedAccountToStore&#160;</td><td class="fielddoc">
<p>Need account for storing files. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3bab1baeceb935584402decd35925a4e443"></a>FileUnavailable&#160;</td><td class="fielddoc">
<p>Requested action not taken, file unavailable. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3ba54368544faf2ec0bfde88dded6920dfc"></a>PageTypeUnknown&#160;</td><td class="fielddoc">
<p>Requested action aborted, page type unknown. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3bab65332f3729d28c9f2551dfa2827dc0c"></a>NotEnoughMemory&#160;</td><td class="fielddoc">
<p>Requested file action aborted, exceeded storage allocation. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3ba84de438a2c6c6bf461c1bc2f79eba577"></a>FilenameNotAllowed&#160;</td><td class="fielddoc">
<p>Requested action not taken, file name not allowed. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3ba2832369b24738d47a832361b09fef964"></a>InvalidResponse&#160;</td><td class="fielddoc">
<p>Not part of the FTP standard, generated by SFML when a received response cannot be parsed. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3ba099e88e94cf51258fd901177a37f7bb7"></a>ConnectionFailed&#160;</td><td class="fielddoc">
<p>Not part of the FTP standard, generated by SFML when the low-level socket connection with the server fails. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3baf84c1847c12fe7216eca9a49af1b0cd7"></a>ConnectionClosed&#160;</td><td class="fielddoc">
<p>Not part of the FTP standard, generated by SFML when the low-level socket connection is unexpectedly closed. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3ba94f4054b5814eb4fe0fc6d576376503a"></a>InvalidFile&#160;</td><td class="fielddoc">
<p>Not part of the FTP standard, generated by SFML when a local file cannot be read or written. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3ba9c0f2a9ad7404aa610eb835ba06724a4"></a>RestartMarkerReply&#160;</td><td class="fielddoc">
<p>Restart marker reply. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3ba68f0497585e490250bc2985edb4201d3"></a>ServiceReadySoon&#160;</td><td class="fielddoc">
<p>Service ready in N minutes. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3bac40df58b564d1256c9dc7cbdaede9ad2"></a>DataConnectionAlreadyOpened&#160;</td><td class="fielddoc">
<p>Data connection already opened, transfer starting. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3bab31a5cb621b4097247dfd59565ae8b98"></a>OpeningDataConnection&#160;</td><td class="fielddoc">
<p>File status ok, about to open data connection. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3bac4a1be25f02eef9d4c28755d40e73fcc"></a>Ok&#160;</td><td class="fielddoc">
<p>Command ok. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3ba4c9c5b2f0c45843fb21139636ac65334"></a>PointlessCommand&#160;</td><td class="fielddoc">
<p>Command not implemented. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3baa179c6310d607c920b23a2d6ce2d61a7"></a>SystemStatus&#160;</td><td class="fielddoc">
<p>System status, or system help reply. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3ba01821e4dc199adbf69ef65df4f949da7"></a>DirectoryStatus&#160;</td><td class="fielddoc">
<p>Directory status. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3ba5b006cb170dda08ade062b4fe1929927"></a>FileStatus&#160;</td><td class="fielddoc">
<p>File status. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3ba90cc40f06a165f2eef3036f5a63ccad4"></a>HelpMessage&#160;</td><td class="fielddoc">
<p>Help message. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3baf9f5fd830fbc98405658fcdd1ed4b958"></a>SystemType&#160;</td><td class="fielddoc">
<p>NAME system type, where NAME is an official system name from the list in the Assigned Numbers document. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3ba94cd5a9201b7ebf0c10739860614e38a"></a>ServiceReady&#160;</td><td class="fielddoc">
<p>Service ready for new user. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3bae070a7c775b991e22bbc94164c06a3e1"></a>ClosingConnection&#160;</td><td class="fielddoc">
<p>Service closing control connection. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3baca24974cc31d5076fb34effeb7c37459"></a>DataConnectionOpened&#160;</td><td class="fielddoc">
<p>Data connection open, no transfer in progress. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3ba326e2020413f73ab20d96e1425dc6c61"></a>ClosingDataConnection&#160;</td><td class="fielddoc">
<p>Closing data connection, requested file action successful. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3ba772b171084e6352b039a3190edd49d47"></a>EnteringPassiveMode&#160;</td><td class="fielddoc">
<p>Entering passive mode. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3baed6a77a3599d7d2c99261e8fd67ddc02"></a>LoggedIn&#160;</td><td class="fielddoc">
<p>User logged in, proceed. Logged out if appropriate. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3ba533ecde0d9d9fb8ced97451dafe478f4"></a>FileActionOk&#160;</td><td class="fielddoc">
<p>Requested file action ok. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3ba469897826bb8b8139df17bc60e584df1"></a>DirectoryOk&#160;</td><td class="fielddoc">
<p>PATHNAME created. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3baeb7f26cf02a13fc05d9e1d8a323b1dde"></a>NeedPassword&#160;</td><td class="fielddoc">
<p>User name ok, need password. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3baa8c41b24d7fba52b82600c74929a7d8c"></a>NeedAccountToLogIn&#160;</td><td class="fielddoc">
<p>Need account for login. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3ba3e7c902cae306df22540129d1b9c3731"></a>NeedInformation&#160;</td><td class="fielddoc">
<p>Requested file action pending further information. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3ba831d98246d1bf42ce95e7f75bb34d485"></a>ServiceUnavailable&#160;</td><td class="fielddoc">
<p>Service not available, closing control connection. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3ba0b82e3e39aa5ce3e9b3115abd04c74cf"></a>DataConnectionUnavailable&#160;</td><td class="fielddoc">
<p>Can't open data connection. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3ba05e7e2eb62bf7d8709f5f6d37dbde7cb"></a>TransferAborted&#160;</td><td class="fielddoc">
<p>Connection closed, transfer aborted. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3ba2d2f79c754ef2257e4e3ad96985506b4"></a>FileActionAborted&#160;</td><td class="fielddoc">
<p>Requested file action not taken. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3ba5400391612ec91f15e64255a4c55b3c3"></a>LocalError&#160;</td><td class="fielddoc">
<p>Requested action aborted, local error in processing. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3bac5e00c7cb975030504b2afb86e47fa68"></a>InsufficientStorageSpace&#160;</td><td class="fielddoc">
<p>Requested action not taken; insufficient storage space in system, file unavailable. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3ba4ccd31337b9478c6cf5089523e16b540"></a>CommandUnknown&#160;</td><td class="fielddoc">
<p>Syntax error, command unrecognized. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3ba00a8672a96112ad00dc2f1117e1146ac"></a>ParametersUnknown&#160;</td><td class="fielddoc">
<p>Syntax error in parameters or arguments. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3bac91eba896240e927206c386f5bf8e32e"></a>CommandNotImplemented&#160;</td><td class="fielddoc">
<p>Command not implemented. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3ba0547dfb381e953f77b7c5a2733c40613"></a>BadCommandSequence&#160;</td><td class="fielddoc">
<p>Bad sequence of commands. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3ba91b4fde3e5e13d59a08c06310b29028d"></a>ParameterNotImplemented&#160;</td><td class="fielddoc">
<p>Command not implemented for that parameter. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3ba4d55199035de3c613fff260681ca762e"></a>NotLoggedIn&#160;</td><td class="fielddoc">
<p>Not logged in. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3baa19655e1a74e69425758933af91d0c65"></a>NeedAccountToStore&#160;</td><td class="fielddoc">
<p>Need account for storing files. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3bab1baeceb935584402decd35925a4e443"></a>FileUnavailable&#160;</td><td class="fielddoc">
<p>Requested action not taken, file unavailable. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3ba54368544faf2ec0bfde88dded6920dfc"></a>PageTypeUnknown&#160;</td><td class="fielddoc">
<p>Requested action aborted, page type unknown. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3bab65332f3729d28c9f2551dfa2827dc0c"></a>NotEnoughMemory&#160;</td><td class="fielddoc">
<p>Requested file action aborted, exceeded storage allocation. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3ba84de438a2c6c6bf461c1bc2f79eba577"></a>FilenameNotAllowed&#160;</td><td class="fielddoc">
<p>Requested action not taken, file name not allowed. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3ba2832369b24738d47a832361b09fef964"></a>InvalidResponse&#160;</td><td class="fielddoc">
<p>Not part of the FTP standard, generated by SFML when a received response cannot be parsed. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3ba099e88e94cf51258fd901177a37f7bb7"></a>ConnectionFailed&#160;</td><td class="fielddoc">
<p>Not part of the FTP standard, generated by SFML when the low-level socket connection with the server fails. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3baf84c1847c12fe7216eca9a49af1b0cd7"></a>ConnectionClosed&#160;</td><td class="fielddoc">
<p>Not part of the FTP standard, generated by SFML when the low-level socket connection is unexpectedly closed. </p>
</td></tr>
<tr><td class="fieldname"><a class="anchor" id="af81738f06b6f571761696291276acb3ba94f4054b5814eb4fe0fc6d576376503a"></a>InvalidFile&#160;</td><td class="fielddoc">
<p>Not part of the FTP standard, generated by SFML when a local file cannot be read or written. </p>
</td></tr>
</table>

<p>Definition at line <a class="el" href="shared_2include_2SFML_2Network_2Ftp_8hpp_source.php#l00074">74</a> of file <a class="el" href="shared_2include_2SFML_2Network_2Ftp_8hpp_source.php">shared/include/SFML/Network/Ftp.hpp</a>.</p>

</div>
</div>
<h2 class="groupheader">Constructor &amp; Destructor Documentation</h2>
<a class="anchor" id="a7e98d0aed70105c71adb52e5b6ce0bb8"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">sf::Ftp::ListingResponse::ListingResponse </td>
          <td>(</td>
          <td class="paramtype">const <a class="el" href="classsf_1_1Ftp_1_1Response.php">Response</a> &amp;&#160;</td>
          <td class="paramname"><em>response</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">const std::string &amp;&#160;</td>
          <td class="paramname"><em>data</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Default constructor. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">response</td><td>Source response </td></tr>
    <tr><td class="paramname">data</td><td>Data containing the raw listing </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a7e98d0aed70105c71adb52e5b6ce0bb8"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">sf::Ftp::ListingResponse::ListingResponse </td>
          <td>(</td>
          <td class="paramtype">const <a class="el" href="classsf_1_1Ftp_1_1Response.php">Response</a> &amp;&#160;</td>
          <td class="paramname"><em>response</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">const std::string &amp;&#160;</td>
          <td class="paramname"><em>data</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Default constructor. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">response</td><td>Source response </td></tr>
    <tr><td class="paramname">data</td><td>Data containing the raw listing </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<h2 class="groupheader">Member Function Documentation</h2>
<a class="anchor" id="a5f0771b52a966bf25b33a70602b6f97f"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">const std::vector&lt;std::string&gt;&amp; sf::Ftp::ListingResponse::getListing </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Return the array of directory/file names. </p>
<dl class="section return"><dt>Returns</dt><dd>Array containing the requested listing </dd></dl>

</div>
</div>
<a class="anchor" id="a5f0771b52a966bf25b33a70602b6f97f"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">const std::vector&lt;std::string&gt;&amp; sf::Ftp::ListingResponse::getListing </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Return the array of directory/file names. </p>
<dl class="section return"><dt>Returns</dt><dd>Array containing the requested listing </dd></dl>

</div>
</div>
<a class="anchor" id="a0015675c528a4a84a671484b9e5499d6"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">const std::string&amp; sf::Ftp::Response::getMessage </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inherited</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>Get the full message contained in the response. </p>
<dl class="section return"><dt>Returns</dt><dd>The response message </dd></dl>

</div>
</div>
<a class="anchor" id="a0015675c528a4a84a671484b9e5499d6"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">const std::string&amp; sf::Ftp::Response::getMessage </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inherited</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>Get the full message contained in the response. </p>
<dl class="section return"><dt>Returns</dt><dd>The response message </dd></dl>

</div>
</div>
<a class="anchor" id="ac7f937b3883d1c4fbc75c003a1786aaa"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3b">Status</a> sf::Ftp::Response::getStatus </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inherited</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>Get the status code of the response. </p>
<dl class="section return"><dt>Returns</dt><dd>Status code </dd></dl>

</div>
</div>
<a class="anchor" id="ac7f937b3883d1c4fbc75c003a1786aaa"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="classsf_1_1Ftp_1_1Response.php#af81738f06b6f571761696291276acb3b">Status</a> sf::Ftp::Response::getStatus </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inherited</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>Get the status code of the response. </p>
<dl class="section return"><dt>Returns</dt><dd>Status code </dd></dl>

</div>
</div>
<a class="anchor" id="a4dadbe0fe0a3ef2d571a017e1645e675"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">bool sf::Ftp::Response::isOk </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inherited</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>Check if the status code means a success. </p>
<p>This function is defined for convenience, it is equivalent to testing if the status code is &lt; 400.</p>
<dl class="section return"><dt>Returns</dt><dd>True if the status is a success, false if it is a failure </dd></dl>

</div>
</div>
<a class="anchor" id="a4dadbe0fe0a3ef2d571a017e1645e675"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">bool sf::Ftp::Response::isOk </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inherited</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>Check if the status code means a success. </p>
<p>This function is defined for convenience, it is equivalent to testing if the status code is &lt; 400.</p>
<dl class="section return"><dt>Returns</dt><dd>True if the status is a success, false if it is a failure </dd></dl>

</div>
</div>
<hr/>The documentation for this class was generated from the following file:<ul>
<li><a class="el" href="include_2SFML_2Network_2Ftp_8hpp_source.php">include/SFML/Network/Ftp.hpp</a></li>
</ul>
</div><!-- contents -->
<?php
    require("../footer-fr.php");
?>
