<?php
    $version = '2.6.0'; // the $ projectnumber variable is automatically replaced by doxygen with the version number
    $pagetitle = 'Class Members'; // the $ title variable is automatically replaced by doxygen with the page title
    include('../header-fr.php');
?>
<!-- Generated by Doxygen 1.9.6 -->
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:d3d9a9a6595521f9666a5e94cc830dab83b65699&amp;dn=expat.txt MIT */
var searchBox = new SearchBox("searchBox", "search/",'.php');
/* @license-end */
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="pages.php"><span>Related&#160;Pages</span></a></li>
      <li><a href="modules.php"><span>Modules</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <span id="MSearchSelect"                onmouseover="return searchBox.OnSearchSelectShow()"                onmouseout="return searchBox.OnSearchSelectHide()">&#160;</span>
          <input type="text" id="MSearchField" value="" placeholder="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.svg" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="classes.php"><span>Class&#160;Index</span></a></li>
      <li><a href="hierarchy.php"><span>Class&#160;Hierarchy</span></a></li>
      <li class="current"><a href="functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
  <div id="navrow3" class="tabs2">
    <ul class="tablist">
      <li class="current"><a href="functions.php"><span>All</span></a></li>
      <li><a href="functions_func.php"><span>Functions</span></a></li>
      <li><a href="functions_vars.php"><span>Variables</span></a></li>
      <li><a href="functions_type.php"><span>Typedefs</span></a></li>
      <li><a href="functions_enum.php"><span>Enumerations</span></a></li>
      <li><a href="functions_eval.php"><span>Enumerator</span></a></li>
      <li><a href="functions_rela.php"><span>Related&#160;Functions</span></a></li>
    </ul>
  </div>
  <div id="navrow4" class="tabs3">
    <ul class="tablist">
      <li class="current"><a href="functions.php#index_a"><span>a</span></a></li>
      <li><a href="functions_b.php#index_b"><span>b</span></a></li>
      <li><a href="functions_c.php#index_c"><span>c</span></a></li>
      <li><a href="functions_d.php#index_d"><span>d</span></a></li>
      <li><a href="functions_e.php#index_e"><span>e</span></a></li>
      <li><a href="functions_f.php#index_f"><span>f</span></a></li>
      <li><a href="functions_g.php#index_g"><span>g</span></a></li>
      <li><a href="functions_h.php#index_h"><span>h</span></a></li>
      <li><a href="functions_i.php#index_i"><span>i</span></a></li>
      <li><a href="functions_j.php#index_j"><span>j</span></a></li>
      <li><a href="functions_k.php#index_k"><span>k</span></a></li>
      <li><a href="functions_l.php#index_l"><span>l</span></a></li>
      <li><a href="functions_m.php#index_m"><span>m</span></a></li>
      <li><a href="functions_n.php#index_n"><span>n</span></a></li>
      <li><a href="functions_o.php#index_o"><span>o</span></a></li>
      <li><a href="functions_p.php#index_p"><span>p</span></a></li>
      <li><a href="functions_q.php#index_q"><span>q</span></a></li>
      <li><a href="functions_r.php#index_r"><span>r</span></a></li>
      <li><a href="functions_s.php#index_s"><span>s</span></a></li>
      <li><a href="functions_t.php#index_t"><span>t</span></a></li>
      <li><a href="functions_u.php#index_u"><span>u</span></a></li>
      <li><a href="functions_v.php#index_v"><span>v</span></a></li>
      <li><a href="functions_w.php#index_w"><span>w</span></a></li>
      <li><a href="functions_x.php#index_x"><span>x</span></a></li>
      <li><a href="functions_y.php#index_y"><span>y</span></a></li>
      <li><a href="functions_z.php#index_z"><span>z</span></a></li>
      <li><a href="functions_~.php#index__7E"><span>~</span></a></li>
    </ul>
  </div>
</div><!-- top -->
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<div id="MSearchResults">
<div class="SRPage">
<div id="SRIndex">
<div id="SRResults"></div>
<div class="SRStatus" id="Loading">Loading...</div>
<div class="SRStatus" id="Searching">Searching...</div>
<div class="SRStatus" id="NoMatches">No Matches</div>
</div>
</div>
</div>
</div>

<div class="contents">
<div class="textblock">Here is a list of all documented class members with links to the class documentation for each member:</div>

<h3><a id="index_a" name="index_a"></a>- a -</h3><ul>
<li>a&#160;:&#160;<a class="el" href="classsf_1_1Color.php#a56dbdb47d5f040d9b78ac6a0b8b3a831">sf::Color</a></li>
<li>A&#160;:&#160;<a class="el" href="classsf_1_1Keyboard.php#acb4cacd7cc5802dec45724cf3314a142a9d06fa7ac9af597034ea724fb08b991e">sf::Keyboard</a>, <a class="el" href="structsf_1_1Keyboard_1_1Scan.php#aa42fbf6954d6f81f7606e566c7abe875af835596d7ce007d5c34c356dee6740c6">sf::Keyboard::Scan</a></li>
<li>Accelerometer&#160;:&#160;<a class="el" href="classsf_1_1Sensor.php#a687375af3ab77b818fca73735bcaea84a11bc58199593e217de23641755ecc867">sf::Sensor</a></li>
<li>accept()&#160;:&#160;<a class="el" href="classsf_1_1TcpListener.php#ae2c83ce5a64d50b68180c46bef0a7346">sf::TcpListener</a></li>
<li>Accepted&#160;:&#160;<a class="el" href="classsf_1_1Http_1_1Response.php#a663e071978e30fbbeb20ed045be874d8ad328945457bd2f0d65107ba6b5ccd443">sf::Http::Response</a></li>
<li>Add&#160;:&#160;<a class="el" href="structsf_1_1BlendMode.php#a7bce470e2e384c4f9c8d9595faef7c32a50c081d8f36cf7b77632966e15d38966">sf::BlendMode</a>, <a class="el" href="classsf_1_1Keyboard.php#acb4cacd7cc5802dec45724cf3314a142a158c586cbe8609031d1a7932e1a8dba2">sf::Keyboard</a></li>
<li>add()&#160;:&#160;<a class="el" href="classsf_1_1SocketSelector.php#ade952013232802ff7b9b33668f8d2096">sf::SocketSelector</a></li>
<li>advance&#160;:&#160;<a class="el" href="classsf_1_1Glyph.php#aeac19b97ec11409147191606b784deda">sf::Glyph</a></li>
<li>alphaDstFactor&#160;:&#160;<a class="el" href="structsf_1_1BlendMode.php#aaf85b6b7943181cc81745569c4851e4e">sf::BlendMode</a></li>
<li>alphaEquation&#160;:&#160;<a class="el" href="structsf_1_1BlendMode.php#a68f5a305e0912946f39ba6c9265710c4">sf::BlendMode</a></li>
<li>alphaSrcFactor&#160;:&#160;<a class="el" href="structsf_1_1BlendMode.php#aa94e44f8e1042a7357e8eff78c61a1be">sf::BlendMode</a></li>
<li>AlResource()&#160;:&#160;<a class="el" href="classsf_1_1AlResource.php#a51b4f3a825c5d68386f8683e3e1053d7">sf::AlResource</a></li>
<li>alt&#160;:&#160;<a class="el" href="structsf_1_1Event_1_1KeyEvent.php#a915a483317de67d995188a855701fbd7">sf::Event::KeyEvent</a></li>
<li>antialiasingLevel&#160;:&#160;<a class="el" href="structsf_1_1ContextSettings.php#ac4a097be18994dba38d73f36b0418bdc">sf::ContextSettings</a></li>
<li>Any&#160;:&#160;<a class="el" href="classsf_1_1IpAddress.php#a3dbc10b0dc6804cc69e29342f7406907">sf::IpAddress</a></li>
<li>AnyPort&#160;:&#160;<a class="el" href="classsf_1_1Socket.php#aa3e6c984bcb81a35234dcc9cc8369d75a5a3c30fd128895403afc11076f461b19">sf::Socket</a></li>
<li>Apostrophe&#160;:&#160;<a class="el" href="classsf_1_1Keyboard.php#acb4cacd7cc5802dec45724cf3314a142a77b44e1f040360d71126fa1c4ad12bec">sf::Keyboard</a>, <a class="el" href="structsf_1_1Keyboard_1_1Scan.php#aa42fbf6954d6f81f7606e566c7abe875ac391cefe75135833aea37c75293db820">sf::Keyboard::Scan</a></li>
<li>append()&#160;:&#160;<a class="el" href="classsf_1_1Packet.php#a7dd6e429b87520008326c4d71f1cf011">sf::Packet</a>, <a class="el" href="classsf_1_1VertexArray.php#a80c8f6865e53bd21fc6cb10fffa10035">sf::VertexArray</a></li>
<li>Application&#160;:&#160;<a class="el" href="structsf_1_1Keyboard_1_1Scan.php#aa42fbf6954d6f81f7606e566c7abe875a5a7f9d3ad8d2528dc7648b682b069211">sf::Keyboard::Scan</a></li>
<li>Arrow&#160;:&#160;<a class="el" href="classsf_1_1Cursor.php#ab9ab152aec1f8a4955e34ccae08f930aa8d9a9cd284dabb4246ab4f147ba779a3">sf::Cursor</a></li>
<li>ArrowWait&#160;:&#160;<a class="el" href="classsf_1_1Cursor.php#ab9ab152aec1f8a4955e34ccae08f930aa16c3acb967f2175434d6bbad7f1300bf">sf::Cursor</a></li>
<li>Ascii&#160;:&#160;<a class="el" href="classsf_1_1Ftp.php#a1cd6b89ad23253f6d97e6d4ca4d558cbac9e544a22dce8ef3177449cb235d15c2">sf::Ftp</a></li>
<li>asMicroseconds()&#160;:&#160;<a class="el" href="classsf_1_1Time.php#a000c2c64b74658ebd228b9294a464275">sf::Time</a></li>
<li>asMilliseconds()&#160;:&#160;<a class="el" href="classsf_1_1Time.php#aa16858ca030a07eb18958c321f256e5a">sf::Time</a></li>
<li>asSeconds()&#160;:&#160;<a class="el" href="classsf_1_1Time.php#aa3df2f992d0b0041b4eb02258d43f0e3">sf::Time</a></li>
<li>Attribute&#160;:&#160;<a class="el" href="structsf_1_1ContextSettings.php#af2e91e57e8d26c40afe2ec8efaa32a2c">sf::ContextSettings</a></li>
<li>attributeFlags&#160;:&#160;<a class="el" href="structsf_1_1ContextSettings.php#a0ef3fc53802bc0197d2739466915ada5">sf::ContextSettings</a></li>
<li>axis&#160;:&#160;<a class="el" href="structsf_1_1Event_1_1JoystickMoveEvent.php#add22e8126b7974271991dc6380cbdee3">sf::Event::JoystickMoveEvent</a></li>
<li>Axis&#160;:&#160;<a class="el" href="classsf_1_1Joystick.php#a48db337092c2e263774f94de6d50baa7">sf::Joystick</a></li>
<li>AxisCount&#160;:&#160;<a class="el" href="classsf_1_1Joystick.php#aee00dd432eacd8369d279b47c3ab4cc5accf3e487c9f6ee2f384351323626a42c">sf::Joystick</a></li>
</ul>
</div><!-- contents -->
<?php
    require("../footer-fr.php");
?>
